### ISSUE TITLE
tqdm object error

### ISSUE THREAD

**Issue by timp0** [nanoporetech/megalodon#105]
Hi,

so when running:
`!megalodon subset_f5 --processes 10 --outputs mappings variants variant_mappings per_read_variants \
    --reference {ref} --variant-filename {variants} --output-directory try1 \
    --guppy-server-path /usr/bin/guppy_basecall_server --reads-per-guppy-batch 10`

I get the following error:
`Traceback (most recent call last):
  File "/home/timp/miniconda3/envs/megalodon/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/timp/miniconda3/envs/megalodon/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/timp/miniconda3/envs/megalodon/lib/python3.6/site-packages/megalodon/megalodon.py", line 564, in _get_fail_queue
    last_err_write)
  File "/home/timp/miniconda3/envs/megalodon/lib/python3.6/site-packages/megalodon/megalodon.py", line 485, in update_prog
    err_statuses[err_num].set_description_str(err_status)
AttributeError: 'tqdm' object has no attribute 'set_description_str'`

Followed by a "failed_reads Getter queue has unexpectedly died likely via segfault"

I looked at the log and guppy server log - so it's seeming to connect.  Not sure exactly what the issue is.

I am running this on a CPU machine, but it seems like the server is getting client connection requests that are timing out?

FYI this is a subset of about 10,000 reads (in multif5) so it shouldn't be overloading anything

Logs attached:
[guppy_basecall_server_log-2021-02-24_21-30-19.log](https://github.com/nanoporetech/megalodon/files/6045777/guppy_basecall_server_log-2021-02-24_21-30-19.log)

[log.txt](https://github.com/nanoporetech/megalodon/files/6045775/log.txt)

**Comment by marcus1487** [comment]
For the tqdm error, what version of tqdm do you have installed? I don't have a lower bound on that package, so it may be that an older version does not have this feature.

It does looks like the server may be overloaded though. The megalodon defaults are set for optimal GPU performance. These settings often don't work well for CPU settings. I would recommend using `--guppy-timeout 500 --reads-per-guppy-batch 10`.

The next version of megalodon should have more robust processing on CPU resources.

**Comment by timp0** [comment]
1) apparently tqdm 4.7.2 - I'm doing all this in a conda env.

2) This setting helped, thanks.  I also tried on a gpu machine and it ran without issue, so your identification of the CPU specific issue was correct.

I have new problems but will raise in a separate issue.

**Comment by liuyangzzu** [comment]
Dear all,
I also faced the same error, I use megalodon 2.3.4, my tqdm version is:
```
pip show tqdm
Name: tqdm
Version: 4.7.2
Summary: A Fast, Extensible Progress Meter
Home-page: https://github.com/tqdm/tqdm
Author: tqdm developers
Author-email: python.tqdm@gmail.com
License: MPLv2.0, MIT Licenses
Location: /opt/conda/envs/nanome/lib/python3.6/site-packages/tqdm-4.7.2-py3.6.egg
Requires:
Required-by: ont-tombo, megalodon
```

My megalodon program generate below error message:

```
Command error:


                                               Process failed_reads:
  Traceback (most recent call last):
    File "/opt/conda/envs/nanome/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
      self.run()
    File "/opt/conda/envs/nanome/lib/python3.6/multiprocessing/process.py", line 93, in run
      self._target(*self._args, **self._kwargs)
    File "/opt/conda/envs/nanome/lib/python3.6/site-packages/megalodon/megalodon.py", line 833, in _get_fail_queue
      last_err_write,
    File "/opt/conda/envs/nanome/lib/python3.6/site-packages/megalodon/megalodon.py", line 717, in update_prog
      err_statuses[err_num].set_description_str(err_status)
  AttributeError: 'tqdm' object has no attribute 'set_description_str'

  Traceback (most recent call last):
    File "/opt/conda/envs/nanome/bin/megalodon", line 8, in <module>
      sys.exit(_main())
    File "/opt/conda/envs/nanome/lib/python3.6/site-packages/megalodon/__main__.py", line 691, in _main
      megalodon._main(args)
    File "/opt/conda/envs/nanome/lib/python3.6/site-packages/megalodon/megalodon.py", line 1781, in _main
      ref_out_info,
    File "/opt/conda/envs/nanome/lib/python3.6/site-packages/megalodon/megalodon.py", line 1165, in process_all_reads
      input_info,
    File "/opt/conda/envs/nanome/lib/python3.6/site-packages/megalodon/megalodon.py", line 992, in wait_for_completion
      getter_qpc.conn.send(True)
    File "/opt/conda/envs/nanome/lib/python3.6/multiprocessing/connection.py", line 206, in send
      self._send_bytes(_ForkingPickler.dumps(obj))
    File "/opt/conda/envs/nanome/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
      self._send(header + buf)
    File "/opt/conda/envs/nanome/lib/python3.6/multiprocessing/connection.py", line 368, in _send
      n = write(self._handle, buf)
  BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by EasonZzZz** [comment]
I degraded tqdm to 4.62.3, and it worked. So I think it maybe caused by tqdm 4.7.2.
