### ISSUE TITLE
ModuleNotFoundError: No module named 'pyguppy_client_lib'

### ISSUE THREAD

**Issue by MeHelmy** [nanoporetech/megalodon#132]
I have a data run using PromethION
we used library kit SQK-LSK109 and flow-cell  FLO-PRO002
normally when I use Guppy I use this config file  dna_r9.4.1_450bps_hac_prom.cfg

I  am new to Megalodon.

Here is the script I am using
```
fastq5_dir=$1
ref=$2

megalodon \
    "${fastq5_dir}" \
    --sort-mappings \
    --outputs  basecalls  mappings mod_mappings mods variants \
    --reference "${ref}" --mod-motif m CG 0 \
    --devices 0 1 --processes 40
```

It gave me this error:

```
[12:54:21] Running Megalodon version 2.3.0
[12:54:21] Loading guppy basecalling backend
Traceback (most recent call last):
  File "/data/medhat/source/conda_installation/envs/basecalling/bin/megalodon", line 11, in <module>
    sys.exit(_main())
  File "/data/medhat/source/conda_installation/envs/basecalling/lib/python3.8/site-packages/megalodon/__main__.py", line 683, in _main
    megalodon._main(args)
  File "/data/medhat/source/conda_installation/envs/basecalling/lib/python3.8/site-packages/megalodon/megalodon.py", line 1752, in _main
    model_info = backends.ModelInfo(backend_params, args.processes)
  File "/data/medhat/source/conda_installation/envs/basecalling/lib/python3.8/site-packages/megalodon/backends.py", line 545, in __init__
    self.pyguppy_load_settings()
  File "/data/medhat/source/conda_installation/envs/basecalling/lib/python3.8/site-packages/megalodon/backends.py", line 999, in pyguppy_load_settings
    from pyguppy_client_lib.pyclient import PyGuppyClient
ModuleNotFoundError: No module named 'pyguppy_client_lib'

```

I changed the script to:

I additionally added this configuration `res_dna_r941_prom_modbases_5mC_CpG_v001.cf` please let me know if this is not the right one based on the flow cell and kit I mentioned earlier.

```
fastq5_dir=$1
ref=$2

megalodon \
    "${fastq5_dir}" \
    --guppy-params "-d ./rerio/basecall_models/" \
    --guppy-config res_dna_r941_prom_modbases_5mC_CpG_v001.cfg \
    --sort-mappings \
    --guppy-server-path /usr/bin/guppy_basecall_server \
    --outputs  basecalls  mappings mod_mappings mods variants \
    --reference "${ref}" --mod-motif m CG 0 \
    --devices 0 1 --processes 40
```

Yet, it gave the same error as above.

Any idea?

Thanks

**Comment by marcus1487** [comment]
This looks like the `ont_pyguppy_client_lib` prerequisite is not installed. You can install the most recent version with `pip install ont_pyguppy_client_lib`. This should have been installed when megalodon was installed though. How did you install megalodon?

**Comment by MeHelmy** [comment]
I used conda  `conda install  megalodon`
and looks like it worked ok:
```
megalodon -v
Megalodon version: 2.3.0
```
I will try your suggestion and give feedback.
Thanks

**Comment by marcus1487** [comment]
Ah pyguppy client lib is not available via conda. See the README for instructions regarding installation via conda.

**Comment by MeHelmy** [comment]
Thank you, 
even though after using your suggestions I have two issues:

A warning:
```
WARNING: Guppy and pyguppy minor versions do not match. This may lead to a failure. Install matching pyguppy version via `pip install ont-pyguppy-client-lib==4.3.4`.
```
and an error
```
ERROR: Error connecting to Guppy server. Undefined error: "Failed to establish connection: [bad_reply] Could not interpret message from server for request: LOAD_CONFIG. Reply: INVALID_PROTOCOL"
```

I think I will go to try to install with `pip` from the starts.
Thanks,
Medhat
