### ISSUE TITLE
Megalodon Incompatibility with Guppy 5.0.7

### ISSUE THREAD

**Issue by marcus1487** [nanoporetech/megalodon#146]
Megalodon is not compatible with the recent Guppy 5.0.7 release. Restoring this compatibility is a very high priority and a fix is currently underway. If run with Guppy 5.0.7, Megalodon will produce the error found at the end of this issue.

The current workaround is to downgrade guppy to the previous release 4.5.4 along with the pyguppy client python package.

Note that due to the nature of this issue, megalodon will not automatically close the guppy server opened within megalodon when this error occurs. These servers must be closed "manually" (I would recommend using top from the command line) or they may start to consume significant resources.

```
[23:36:42] Running Megalodon version 2.3.1
[23:36:42] Loading guppy basecalling backend
Traceback (most recent call last):
  File ".../venv/bin/megalodon", line 33, in <module>
    sys.exit(load_entry_point('megalodon', 'console_scripts', 'megalodon')())
  File ".../megalodon/megalodon/__main__.py", line 683, in _main
    megalodon._main(args)
  File ".../megalodon/megalodon/megalodon.py", line 1752, in _main
    model_info = backends.ModelInfo(backend_params, args.processes)
  File ".../megalodon/megalodon/backends.py", line 545, in __init__
    self.pyguppy_load_settings()
  File ".../megalodon/megalodon/backends.py", line 1006, in pyguppy_load_settings
    self.pyguppy_set_model_attributes(init_sig_len)
  File ".../megalodon/megalodon/backends.py", line 951, in pyguppy_set_model_attributes
    self.pyguppy_basecall([(init_sig_data, None)])
  File ".../megalodon/megalodon/backends.py", line 1130, in pyguppy_basecall
    saved_input_data
  File ".../megalodon/megalodon/backends.py", line 1067, in pyguppy_get_completed_reads
    parse_pyguppy_called_read(called_read),
  File ".../megalodon/megalodon/backends.py", line 299, in parse_pyguppy_called_read
    move=read_datasets["movement"],
KeyError: 'movement'
```

**Comment by marcus1487** [comment]
Resolved with 2.3.3 release.
