### ISSUE TITLE
megalodon_helper.MegaError: Modified bases database already exists. 

### ISSUE THREAD

**Issue by lpryszcz** [nanoporetech/megalodon#15]
Hi, while running megalodon on _E. coli_ dataset from [PRJEB22772](https://www.ebi.ac.uk/ena/data/view/PRJEB22772) I'm getting below error. I'm reporting as the run will take ~5 days and not sure if it makes sense to keep if running.  Any ideas? 

```
$ megalodon PRJEB22772/MARC_ZFscreens_R9.4_1D-Ecoli-run_FAF05145/ --reference ref/mock_community.fa --output-directory megalodon/PRJEB22772/MARC_ZFscreens_R9.4_1D-Ecoli-run_FAF05145 --outputs basecalls mappings mods --devices 0 --verbose-read-progress 3

[17:36:25] Using canonical alphabet ACGT and modified bases Y=6mA Z=5mC.
[17:36:25] Loading reference.
[17:36:27] Preparing workers to process reads.
[17:36:27] Processing reads.
3 most common unsuccessful read types:
     -----
     -----
     -----
0read [00:00, ?read/s]Process Process-5:
Traceback (most recent call last):
  File "/home/lpryszcz/src/miniconda3/lib/python3.7/site-packages/megalodon/mods.py", line 135, in __init__
    '{} {}'.format(*ft) for ft in tbl.items()))))
sqlite3.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lpryszcz/src/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/lpryszcz/src/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lpryszcz/src/miniconda3/lib/python3.7/site-packages/megalodon/mods.py", line 671, in _get_mods_queue
3 most common unsuccessful read types:emory)
    36.9% (   4138 reads) : No alignment                                                                    
     1.7% (    193 reads) : Likely out of memory error.                                                     
     -----megalodon_helper.MegaError: Modified bases database already exists. Either provide location for new database or open in read_only mode.
  2%|██▋                                                                                                                                               | 11249/619525 [2:09:53<117:03:21,  1.44read/s, ksamp/s=167]
```

**Comment by marcus1487** [comment]
I have not seen this error before, but this error will indeed stall the run once the processing queues fill up. Thus the run should be stopped and diagnosed. The caught error here indicates that the database is locked and not that it previously existed. The secondary megalodon error here should likely be updated to indicate this possibility. This seems like some issue with sqlite3, but I have not seen this before. If restarted does this exact same error occur again?

**Comment by lpryszcz** [comment]
Yes, you're right @marcus1487, the ran stalled after nearly 3h (`14455/619525 [2:45:00<115:06:48,  1.46read/s, ksamp/s=158]`). The issue persists when I run again on the same storage in the cluster (tried 5 times).  
I think the issue is due to working in NFS (Isilon) as on local drives (SSD or HDD) the run starts normally. Could it be due to concurrency between processes? NFS has larger I/O lag therefore multiple processes may try to create same db/tables via `sqlite3` since NFS takes little longer to propagate the changes.

**Comment by marcus1487** [comment]
Interesting. I have tested megalodon extensively on HPC environments including over NFS, but have not experienced this issue. I’m wondering if there might be a way to stall the mod database creation until the initialization is complete. This is the first command after the creation of the database connection. I’m off for the next 2 days but I’ll try to push a fix next Monday. 

I will note that the aggregation step will be very slow over NFS. I have seen close to 1000X speed increases on certain systems. In the next release a status note will be added to this effect.

**Comment by marcus1487** [comment]
I've push a couple of minor changes to the mods database interface. I hope these might address the issue here, but without being able to reproduce this I'll need feedback to know if these updates worked. If the same error is observed, could you change the default sqlite3 timeout to a larger value (maybe 30), re-install megalodon and try again ([here](https://github.com/nanoporetech/megalodon/blob/master/megalodon/mods.py#L40) in the code)?

**Comment by marcus1487** [comment]
I've actually just pushed another commit to refactor the sqlite timeout variable. Change that value in the code [here](https://github.com/nanoporetech/megalodon/blob/master/megalodon/megalodon_helper.py#L42) now.

**Comment by lpryszcz** [comment]
Hi @marcus1487 . after `pip install -U git+https://github.com/nanoporetech/megalodon.git` I still see the issue in NFS: 

```
Traceback (most recent call last):
  File "/home/lpryszcz/src/miniconda3/lib/python3.7/site-packages/megalodon/mods.py", line 136, in __init__
    '{} {}'.format(*ft) for ft in tbl.items()))))
sqlite3.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lpryszcz/src/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/lpryszcz/src/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lpryszcz/src/miniconda3/lib/python3.7/site-packages/megalodon/mods.py", line 672, in _get_mods_queue
3 most common unsuccessful read types:emory)
     -----ome/lpryszcz/src/miniconda3/lib/python3.7/site-packages/megalodon/mods.py", line 140, in __init__
     -----de location for new database or open in ' +
     -----megalodon_helper.MegaError: Modified bases database already exists. Either provide location for new database or open in read_only mode.
```

**Comment by marcus1487** [comment]
Sorry for the confusion, `5` is the default. Could you change this value to `60` and see if the command still fails?

**Comment by lpryszcz** [comment]
Hi @marcus1487 , I've tried with 5, 15 and 60, and all the time the error pops up (although with 15 and 60 it appears after 15 or 60 seconds, respectively). It even appears when running single process, which is weird, right? 

```
SQLITE_TIMEOUT=60
[10:31:10] Using canonical alphabet ACGT and modified bases Y=6mA Z=5mC.
[10:31:10] Loading reference.
[10:31:12] Preparing workers to process reads.
[10:31:12] Processing reads.
3 most common unsuccessful read types:
     1.6% (      1 reads) : No alignment
     -----
     -----
63read [00:59,  1.06read/s, ksamp/s=96.4]Process Process-5:
Traceback (most recent call last):
  File "/home/lpryszcz/src/miniconda3/lib/python3.7/site-packages/megalodon/mods.py", line 136, in __init__
    '{} {}'.format(*ft) for ft in tbl.items())))) 
sqlite3.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lpryszcz/src/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/lpryszcz/src/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lpryszcz/src/miniconda3/lib/python3.7/site-packages/megalodon/mods.py", line 672, in _get_mods_queue
3 most common unsuccessful read types:emory)
     2.9% (      2 reads) : No alignment
     -----de location for new database or open in ' +
     -----megalodon_helper.MegaError: Modified bases database already exists. Either provide location for new database or open in read_only mode.
69read [01:05,  1.06read/s, ksamp/s=95.3]^CProcess Process-3:
```

**Comment by marcus1487** [comment]
This looks potentially like an NFS configuration issue. It looks like you might be able to add the nolock option to the fstab file (see [here](https://github.com/bcbio/bcbio-nextgen/issues/1123#issuecomment-160821592)). Let me know if this resolves your issue.

**Comment by marcus1487** [comment]
Did this workaround solve the issue here?

**Comment by marcus1487** [comment]
Closing due to inactivity.
