### ISSUE TITLE
SyntaxError: invalid syntax - guppy 5.0.7 - megalodon 2.3.3

### ISSUE THREAD

**Issue by mattdmem** [nanoporetech/megalodon#151]
Hello - I'm getting the following error while trying to run v2.3.3 (wintin python 3.7 conda env) with the latest guppy.

```
megalodon workspace --outputs basecalls mappings mod_mappings mods --reference reference.fa --mod-motif Z CG 0 --devices 0  --processes 8 --guppy-server-path ~/wc/ont-guppy_5.0.7/bin/guppy_basecall_server --overwrite
```

```
Traceback (most recent call last):
  File "/home/md1mpar/.local/bin/megalodon", line 8, in <module>
    sys.exit(_main())
  File "/home/md1mpar/.local/lib/python3.5/site-packages/megalodon/__main__.py", line 689, in _main
    from megalodon import megalodon
  File "/home/md1mpar/.local/lib/python3.5/site-packages/megalodon/megalodon.py", line 15, in <module>
    from megalodon import (
  File "/home/md1mpar/.local/lib/python3.5/site-packages/megalodon/backends.py", line 812
    f"{GUPPY_HOST}:{self.params.pyguppy.port}", timeout
                                                                             ^
SyntaxError: invalid syntax
```

Any ideas? Thanks!

**Comment by mattdmem** [comment]
I got it working by destroying my conda env and installing master... not sure the root cause of the issue

**Comment by marcus1487** [comment]
This error is due to that install being linked to python3.5 (not 3.7; see full paths in listed errors). Megalodon has dropped support for python <3.6. I may have missed this in the setup specs, but will fix this in the next release.
