### ISSUE TITLE
ExtractSignalProcessingError

### ISSUE THREAD

**Issue by fidibidi** [nanoporetech/megalodon#154]
Hello!

Running a megalodon on a Promethion dataset, which can be found here (s3://ont-open-data/gm24385_2020.11/flowcells/20201102_1746_6C_PAG07506_acad8a68/fast5_pass/) with descriptions found https://labs.epi2me.io/gm24385_2020.11/. In this case I am using the 	PAG07506 flowcell. 

Ran with this command 
`
/home/fidi/.pyenv/versions/3.6.0/bin/megalodon promION/Prom-4 --guppy-server-path ont-guppy-4.5.2/bin/guppy_basecall_server --output-directory prom-4-meg --overwrite --reference GRCh38.no_alt.mmi --outputs basecalls mappings mod_mappings mods --processes 16 --devices cuda:0 --mod-output-formats modvcf --guppy-timeout 500
`

My plan at the moment is to run the data in groups, since it is so large ~600gb, and merge the outputs as needed. 
I've seen this detailed on these forums, so I don't believe that will be an issue. 

About halfway through, I've hit this error twice now. 

`
        ERROR: ExtractSignalProcessingError

        ERROR: Unable to get link info (incorrect metadatda checksum after all read attempts)

        ERROR: Traceback (most recent call last):
  File "/home/fidi/.pyenv/versions/3.6.0/lib/python3.6/site-packages/megalodon/fast5_io.py", line 205, in _extract_signal_worker
    fast5_fp, read_id, extract_dacs
  File "/home/fidi/.pyenv/versions/3.6.0/lib/python3.6/site-packages/megalodon/backends.py", line 597, in extract_signal_info
    read = fast5_fp.get_read(read_id)
  File "/home/fidi/.pyenv/versions/3.6.0/lib/python3.6/site-packages/ont_fast5_api/multi_fast5.py", line 35, in get_read
    if group_name not in self.handle:
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/fidi/.pyenv/versions/3.6.0/lib/python3.6/site-packages/h5py/_hl/group.py", line 439, in __contains__
    return self._e(name) in self.id
  File "h5py/h5g.pyx", line 462, in h5py.h5g.GroupID.__contains__
  File "h5py/h5g.pyx", line 463, in h5py.h5g.GroupID.__contains__
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5g.pyx", line 532, in h5py.h5g._path_valid
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5l.pyx", line 212, in h5py.h5l.LinkProxy.exists
RuntimeError: Unable to get link info (incorrect metadatda checksum after all read attempts)
`

As I was writing this text, and preparing to attach my logs, I noticed in guppy that there was another error... 

`
2021-06-08 11:08:19.580600 [guppy/info] CUDA device 0 reached memory limit while trying to allocate 1467473408 bytes, currently at 8321543016/10495852544
`

so perhaps this could be the issue. 

[log.txt](https://github.com/nanoporetech/megalodon/files/6619006/log.txt)
[guppy_basecall_server_log-2021-06-08_11-07-54.log](https://github.com/nanoporetech/megalodon/files/6619008/guppy_basecall_server_log-2021-06-08_11-07-54.log)

Any help much appreciated!

**Comment by fidibidi** [comment]
Well, I seem to have resolved the CUDA device 0 memory limit issue, by modifying guppy params. 
However, I'm still getting the above error... 

There seems to have been a new message though as well 
`Traceback (most recent call last):                                                                                            
  File "/home/fidi/.pyenv/versions/3.6.0/lib/python3.6/threading.py", line 916, in _bootstrap_inner6]
    self.run()
  File "/home/fidi/.pyenv/versions/3.6.0/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/fidi/.pyenv/versions/3.6.0/lib/python3.6/site-packages/megalodon/mapping.py", line 370, in _map_read_worker
    align_read(q_seq, aligner, map_thr_buf, read_id, allow_supps)
  File "/home/fidi/.pyenv/versions/3.6.0/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/fidi/.pyenv/versions/3.6.0/lib/python3.6/multiprocessing/connection.py", line 397, in _send_bytes
    self._send(header)
  File "/home/fidi/.pyenv/versions/3.6.0/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
`

**Comment by fidibidi** [comment]
Interestingly, this error doesn't appear when I run smaller portions of the Dataset. 
80000 reads succeeds....

**Comment by marcus1487** [comment]
This looks like a potentially corrupted FAST5 file. My guess would be that this shorter chunk does not have the corrupted file/read. There isn't a great way to sort out which file has failed as megalodon does not report when it has started searching a file for reads, but only once it has completed the processing for a file.

**Comment by fidibidi** [comment]
Thanks. Hopefully one of these works...

**Comment by marcus1487** [comment]
I've just pushed a fix which should catch the bad signal extraction and log this in the log file (but not to the error queue yet). This should allow your run to complete except for the malformatted read.

You'll have to install from github as this has not yet been included in a release. `pip install git+https://github.com/nanoporetech/megalodon`

**Comment by fidibidi** [comment]
Awesome! 

Thank you so much for putting the time and effort into helping with this issue. 

I'm currently still running the PAF27096 PromethION flowcell, (38hrs in....) and things seem to be going well! 

Excited to see the results.

**Comment by fidibidi** [comment]
Since I haven't re-used that data, and haven't run into the same issue, I will close this for now! Thanks for the help!
