### ISSUE TITLE
Megalodon v2.3.3 possible incompatibility with Guppy v5.0.7 

### ISSUE THREAD

**Issue by misshie** [nanoporetech/megalodon#156]
I am using Megalodon v2.3.3 and Guppy v5.0.7. I still have errors similar to the issue #146 like the followings with PromethION data. If anyone knows workarounds, please share them.

Version infomation is the followings:
```
$ megalodon --version
Megalodon version: 2.3.3
$ guppy_basecall_server --version
: Guppy Basecall Service Software, (C) Oxford Nanopore Technologies, Limited. Version 5.0.7+2332e8d65, client-server API version 7.0.0
```

Errors on a console are the followings:
```
                  Process ReadWorker005:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstraps/s, samples/s=2.37e+7]  
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "[snip]venv/lib/python3.8/site-packages/megalodon/megalodon.py", line 481, in _process_reads_worker
    for bc_res in model_info.iter_basecalled_reads(
  File "[snip]venv/lib/python3.8/site-packages/megalodon/backends.py", line 726, in iter_basecalled_reads
    for bc_res in self.pyguppy_run_model(
  File "[snip]venv/lib/python3.8/site-packages/megalodon/backends.py", line 1280, in pyguppy_run_model
    for called_read, sig_info, seq_summ_info in self.pyguppy_basecall(
  File "[snip]venv/lib/python3.8/site-packages/megalodon/backends.py", line 1129, in pyguppy_basecall
    for comp_read, read_id in self.pyguppy_get_completed_reads(
  File "[snip]lib/python3.8/site-packages/megalodon/backends.py", line 1084, in pyguppy_get_completed_reads
    parse_pyguppy_called_read(called_read),
  File "[snip]lib/python3.8/site-packages/megalodon/backends.py", line 300, in parse_pyguppy_called_read
    move=read_datasets["movement"],
KeyError: 'movement'
```

I got similar error messages for different ReadWorkers (16 errors). The Megalodon process itself did not killed by these errors. The process, however, did not finish automatically and did not generate the modified_bases.5mC.bed file.
```
Read Processing: 100%|     | 27194667/27194814 [30:33:53<00:00, 247.15reads/s, samples/s=2.37e+7] 
```
 I sent SIGTEM to the  guppy_basecall_sever processes but Megalodon did not respond. 

The followings are head lines of the log.txt file.
```
[10:40:46] Running Megalodon version 2.3.3
DBG 10:40:46 : Command: """[snip]venv/bin/megalodon raw_fast5s --guppy-params=-d /staging/rerio/basecall_models --num_callers 16 --ipc_threads 32 --guppy-config res_dna_r941_prom_mod>
[10:40:46] Loading guppy basecalling backend
DBG 10:40:47 : Guppy version: "5.0.7" --- MainProcess-MainThread backends.py:842
DBG 10:40:47 : Pyguppy version: "5.0.7" --- MainProcess-MainThread backends.py:843
DBG 10:40:47 : guppy server init command: "/opt/ont/guppy/bin/guppy_basecall_server -p auto -l /staging/[snip]/guppy_log -c res_dna_r941_prom_modbases_5mC_CpG_v001.cfg --post_out --quiet -x cuda:2 cuda:3 >
DBG 10:40:47 : Found guppy log file: /staging/[snip]/guppy_log/guppy_basecall_server_log-2021-06-15_10-40-47.log --- MainProcess-MainThread backends.py:933
DBG 10:40:50 : Connecting to server --- MainProcess-MainThread backends.py:777
DBG 10:40:50 : pyguppy server status: result.success --- MainProcess-MainThread backends.py:814
DBG 10:40:50 : pyguppy server config: {'/staging/rerio/basecall_models/res_dna_r941_prom_modbases_5mC_CpG_v001.cfg': {'Basecalling': {'ModelFile': 'res_dna_r941_prom_modbases_5mC_CpG_v001.jsn', 'res_dna_r941_prom_modbases_5mC_CpG_v001.>
DBG 10:40:50 : init_test_read BasecallingCompleted --- MainProcess-MainThread backends.py:1082
```

**Comment by marcus1487** [comment]
This looks very related to the issues that arose with guppy 5.0.7. See #146 

It is likely that this fix did not completely address the issues introduced by the guppy 5.0.7 upgrade. I'll have a look at a more thorough fix.

**Comment by misshie** [comment]
Now I am running Megalodon v2.3.3. with Guppy v5.0.11 (released on June 11, 2021) and the newest `ont_pyguppy_client_lib`. I will comment the results here.

**Comment by misshie** [comment]
Unfortunately, the situation does not seem to be changed with Guppy v5.0.11.

**Comment by marcus1487** [comment]
I expected this would be the case. I should be able to add a fix shortly.

**Comment by marcus1487** [comment]
I've just pushed some updates that should address this issue. This is currently only available from an install from github `pip install git+https://github.com/nanoporetech/megalodon`, but will be included in the next release.

**Comment by misshie** [comment]
I will try the combination of the newest Megalodon and the newest Guppy during this week.

**Comment by misshie** [comment]
The combination of the newest Megalodon on Github and Guppy/PyGuppy v5.0.11 worked well in our environment. I appreciate the effort of the Megalodon team!
