### ISSUE TITLE
Can 5hmC and 5mC be called at the same time?

### ISSUE THREAD

**Issue by Shians** [nanoporetech/megalodon#159]
I'm trying to call 5hmC and 5mC simultaneously on some mouse data. I can't figure out how this is meant to be done or if it is possible.

It's not clear how `megalodon_extras modified_bases estimate_threshold` is meant to be run based on the documentation [here](https://nanoporetech.github.io/megalodon/extras_modified_bases.html#megalodon-extras-modified-bases-describe-alphabet) and numerous attempts to run it have resulted in a missing attribute error.

```
megalodon_extras modified_bases describe_alphabet --guppy-server-path ~/LongReadMethylation/Software/downloads/ont-guppy/bin/guppy_basecall_server
Guppy logs output directory exists. Potentially overwriting guppy logs.
[12:41:09] Loading guppy basecalling backend
Traceback (most recent call last):
  File "/home/users/allstaff/su.s/LongReadMethylation/Software/downloads/megalodon/bin/megalodon_extras", line 10, in <module>
    sys.exit(_main())
  File "/home/users/allstaff/su.s/LongReadMethylation/Software/downloads/megalodon/lib/python3.7/site-packages/megalodon_extras/__main__.py", line 230, in _main
    module._main(args)
  File "/home/users/allstaff/su.s/LongReadMethylation/Software/downloads/megalodon/lib/python3.7/site-packages/megalodon_extras/modified_bases_describe_alphabet.py", line 31, in _main
    with backends.ModelInfo(backend_params, 1) as model_info:
  File "/home/users/allstaff/su.s/LongReadMethylation/Software/downloads/megalodon/lib/python3.7/site-packages/megalodon/backends.py", line 545, in __init__
    self.pyguppy_load_settings()
  File "/home/users/allstaff/su.s/LongReadMethylation/Software/downloads/megalodon/lib/python3.7/site-packages/megalodon/backends.py", line 1004, in pyguppy_load_settings
    self.pyguppy_check_version(pyguppy_version_str)
  File "/home/users/allstaff/su.s/LongReadMethylation/Software/downloads/megalodon/lib/python3.7/site-packages/megalodon/backends.py", line 825, in pyguppy_check_version
    'Guppy version string does not match expected pattern: "{}"'
AttributeError: 'MegaError' object has no attribute 'format'
```

Also when using rerio model `res_dna_r941_min_modbases_5mC_5hmC_v001.cfg`, I tried the arguments `--mod-motif h CG 0 --mod-motif m CG 0` to try and call 5hmC and 5mC simultaneously, but this raised the error

```
[14:18:17] Loaded model calls canonical alphabet ACGT and modified bases h=5hmC (alt to C); m=5mC (alt to C)
****************************************************************************************************
        ERROR: One provided motif can be found within another motif. Only distinct sets of motifs are accepted
****************************************************************************************************
```

I had initially called only the `--mod-motif h CG`, which I assumed to mean 5hmC, but when inspecting the results the prevalence is significantly higher than expected, and the general patterns are identical to 5mC.

So I guess I have the following questions:

* What are the arguments of `megalodon_extras modified_bases estimate_threshold` and how is it supposed to run?
* Is it possible to simultaneously call 5hmC and 5mC or does the software need to run twice?
* Are there any reports of the accuracy of 5hmC for mouse samples?

**Comment by marcus1487** [comment]
I don't believe the `megalodon_extras modified_bases estimate_threshold` command is relevant to your goals here. This method is intended to *roughly* estimate the proportion of a modified base present in a sample, and then estimate the optimal threshold in probability space to set the threshold for marking up per-read modified bases calls for modified base model training from this sample and a preliminary model.

For the second question, it is possible to estimate 5mC and 5hmC simultaneously. The issue is with the option syntax. The motif option should specified as `--mod-motif mh CG 0`. The `h` does indeed stand for 5hmC. See the `megalodon_extras modified_bases describe_alphabet` command to confirm this for any model.

I am not aware of any reports of accuracy for the 5hmC model (in mouse or otherwise). Internally, we have circumstantial evidence that the model has power to detect 5hmC due to matching high level biological patterns. This is the reason that this model remains in the research Rerio models repository and has not yet been transferred to the production Guppy basecaller. We are working to obtain better per-read ground truth datasets for 5hmC and will release community notes with the results (and probably an updated model) once we have these.

**Comment by Shians** [comment]
Thanks for the thorough reply, I copy and pasted the wrong command. I had meant to ask about `megalodon_extras modified_bases describe_alphabet` rather than `megalodon_extras modified_bases estimate_threshold`.

I expected the command to look something like `megalodon_extras modified_bases describe_alphabet some_model.cfg` but it's not clear what arguments actually go into this command.

**Comment by marcus1487** [comment]
`megalodon_extras modified_bases describe_alphabet` requires the minimal arguments to load the model (which defines the alphabet). Use the `-h` flag to see full documentation for any megalodon command.

**Comment by Shians** [comment]
Thanks Marcus, that makes sense. Though it took a bit of tinkering to get it to work for a rerio model.

Initially I tried 

```
megalodon_extras modified_bases describe_alphabet --guppy-config res_dna_r941_min_modbases_5mC_5hmC_v001.cfg --guppy-params "-d ../Software/downloads/rerio/basecall_models/"
Guppy logs output directory exists. Potentially overwriting guppy logs.
[15:48:52] Loading guppy basecalling backend
Traceback (most recent call last):
  File "/home/shians/anaconda3/envs/megalodon/bin/megalodon_extras", line 11, in <module>
    sys.exit(_main())
  File "/home/shians/anaconda3/envs/megalodon/lib/python3.8/site-packages/megalodon_extras/__main__.py", line 225, in _main
    module._main(args)
  File "/home/shians/anaconda3/envs/megalodon/lib/python3.8/site-packages/megalodon_extras/modified_bases_describe_alphabet.py", line 31, in _main
    with backends.ModelInfo(backend_params, 1) as model_info:
  File "/home/shians/anaconda3/envs/megalodon/lib/python3.8/site-packages/megalodon/backends.py", line 546, in __init__
    self.pyguppy_load_settings()
  File "/home/shians/anaconda3/envs/megalodon/lib/python3.8/site-packages/megalodon/backends.py", line 1022, in pyguppy_load_settings
    self.pyguppy_start_server()
  File "/home/shians/anaconda3/envs/megalodon/lib/python3.8/site-packages/megalodon/backends.py", line 942, in pyguppy_start_server
    check_server_proc()
  File "/home/shians/anaconda3/envs/megalodon/lib/python3.8/site-packages/megalodon/backends.py", line 883, in check_server_proc
    raise mh.MegaError(
megalodon.megalodon_helper.MegaError: Guppy server initialization failed. See guppy logs in [--output-directory] for more details.
		Try running the guppy server initialization command found in log.txt in order to pinpoint the source of this issue.
```

But when run in this mode, there is no `--output-directory` argument, nor is `megalodon output` created I think. Luckily the second line of the error directed me to the command in `log.txt`

```
./ont-guppy/bin/guppy_basecall_server -p auto -l guppy_logs/guppy_log -c res_dna_r941_min_modbases_5mC_5hmC_v001.cfg --post_out --quiet -d ../Software/downloads/rerio/basecall_models/
[guppy/error] main: Substitution matrix for Minalign class must be 5x5.
```

It's not clear what this means, but in the end I copied the model files from the rerio directory into `ont-guppy/data/` and it provided the desired results

```
megalodon_extras modified_bases describe_alphabet --guppy-config res_dna_r941_min_modbases_5mC_5hmC_v001.cfg
Guppy logs output directory exists. Potentially overwriting guppy logs.
[15:31:01] Loading guppy basecalling backend
[2021-06-25 15:31:03.097412] [0x00007f2ab2f0e640] [info]    Connecting to server as ''
[2021-06-25 15:31:03.098252] [0x00007f2ab2f0e640] [info]    Connected to server as ''. Connection id: 3bb3a685-e328-4066-86fd-575ef62c8720
[15:31:03] Loaded model calls canonical alphabet ACGT and modified bases h=5hmC (alt to C); m=5mC (alt to C)
```

Thanks for your help!
