### ISSUE TITLE
Megalodon v2.3.4 possible incompatibility with Guppy v5.0.11

### ISSUE THREAD

**Issue by misshie** [nanoporetech/megalodon#175]
I continue testing Megalodon v2.3.4 with Guppy v5.0.11 using in-house PromethION data from human whole genome samples.

```
[03:26:27] Running Megalodon version 2.3.4
[03:26:27] Loading guppy basecalling backend
DBG 03:26:28 : Guppy version: "5.0.11" --- MainProcess-MainThread backends.py:869
DBG 03:26:28 : Pyguppy version: "5.0.11" --- MainProcess-MainThread backends.py:870
```

 I found the following error related to issue #156 and #146 :
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "[snip]Megalodon/venv/lib/python3.8/site-packages/megalodon/megalodon.py", line 481, in _process_reads_worker
    for bc_res in model_info.iter_basecalled_reads(
  File "[snip]Megalodon/venv/lib/python3.8/site-packages/megalodon/backends.py", line 752, in iter_basecalled_reads
    for bc_res in self.pyguppy_run_model(
  File "[snip]Megalodon/venv/lib/python3.8/site-packages/megalodon/backends.py", line 1306, in pyguppy_run_model
    for called_read, sig_info, seq_summ_info in self.pyguppy_basecall(
  File "[snip]Megalodon/venv/lib/python3.8/site-packages/megalodon/backends.py", line 1155, in pyguppy_basecall
    for comp_read, read_id in self.pyguppy_get_completed_reads(
  File "[snip]Megalodon/venv/lib/python3.8/site-packages/megalodon/backends.py", line 1110, in pyguppy_get_completed_reads
    parse_pyguppy_called_read(called_read),
  File "[snip]Megalodon/venv/lib/python3.8/site-packages/megalodon/backends.py", line 307, in parse_pyguppy_called_read
    raise mh.MegaError(f"Guppy server returned invalid read: {str(e)}")
megalodon.megalodon_helper.MegaError: Guppy server returned invalid read: 'movement'
```

The error seems to be rare. The error occurred only in 1 of 7 samples (6 samples worked well!). Other symptoms are similar to #156 . Please let me know if more detailed information is required.

**Comment by marcus1487** [comment]
A recent commit (since the 2.3.4 release) has been pushed which should address this issue. If you can install from GitHub and try to run again this issue should be resolved. Please post if this does not resolve the issue.

**Comment by misshie** [comment]
Using Megalodon installed from the master branch on GitHub, this issue was solved!

Megalodon logged possiblly causative 6 reads like the followings: 
```
[09:06:33] Unsuccessful processing types:
     3.0% ( 608756 reads) : No alignment                                                                    
     0.0% (      6 reads) : Guppy server timeout (see --guppy-timeout argument)                             
     0.0% (      6 reads) : Guppy server returned invalid read: 'movement'
```
I appreciate efforts of the Megalodon team.

**Comment by marcus1487** [comment]
Glad to hear the latest fix has resolved this issue! Best of luck in your research!
