### ISSUE TITLE
megalodon basemod TypeError

### ISSUE THREAD

**Issue by etvedte** [nanoporetech/megalodon#19]
Greetings,

I am testing megalodon for base mod calling only on an ecoli sample. Numpy and cython were previously installed, and I ran the following to install megalodon
```
pip install git+https://github.com/nanoporetech/megalodon.git
```
This is the command of my test run:
```
megalodon /path/to/guppy/fast5/workspace/ --outputs mods --reference /path/to/ecoli.genome.fasta --processes 8
```
The job died immediately. The stderr for the job is:
```
Traceback (most recent call last):
  File "/home/etvedte/.local/bin/megalodon", line 8, in <module>
    sys.exit(_main())
  File "/home/etvedte/.local/lib/python3.5/site-packages/megalodon/megalodon.py", line 1118, in _main
    max_concur_chunks=args.max_concurrent_chunks)
  File "/home/etvedte/.local/lib/python3.5/site-packages/megalodon/backends.py", line 234, in __init__
    self._load_fast5_post_out()
  File "/home/etvedte/.local/lib/python3.5/site-packages/megalodon/backends.py", line 162, in _load_fast5_post_out
    self.output_size) = get_model_info_from_fast5(read)
  File "/home/etvedte/.local/lib/python3.5/site-packages/megalodon/backends.py", line 144, in get_model_info_from_fast5
    out_size = fast5_io.get_posteriors(read).shape[1]
  File "/home/etvedte/.local/lib/python3.5/site-packages/megalodon/fast5_io.py", line 61, in get_posteriors
    latest_basecall + '/BaseCalled_template', 'StateData', proxy=False)
TypeError: get_analysis_dataset() got an unexpected keyword argument 'proxy'
```

**Comment by marcus1487** [comment]
This issue is related to the upgrade to ont_fast5_api to version >=3.0.0. This fix will be included in the major release coming soon. As a workaround for now, ont_fast5_api can be downgraded to a version <3.0.0.

**Comment by marcus1487** [comment]
This should be resolved with the 2.0 release. Please re-open if this issue occurs with the current release.

**Comment by avitalsteiman** [comment]
Hi,
I'm getting this error now, after installing with pip last week/

> Traceback (most recent call last):
  File "/usr/local/bin/megalodon", line 10, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.5/dist-packages/megalodon/megalodon.py", line 1118, in _main
    max_concur_chunks=args.max_concurrent_chunks)
  File "/usr/local/lib/python3.5/dist-packages/megalodon/backends.py", line 234, in __init__
    self._load_fast5_post_out()
  File "/usr/local/lib/python3.5/dist-packages/megalodon/backends.py", line 162, in _load_fast5_post_out
    self.output_size) = get_model_info_from_fast5(read)
  File "/usr/local/lib/python3.5/dist-packages/megalodon/backends.py", line 144, in get_model_info_from_fast5
    out_size = fast5_io.get_posteriors(read).shape[1]
  File "/usr/local/lib/python3.5/dist-packages/megalodon/fast5_io.py", line 61, in get_posteriors
    latest_basecall + '/BaseCalled_template', 'StateData', proxy=False)
TypeError: get_analysis_dataset() got an unexpected keyword argument 'proxy'

My command was: 
` megalodon  fast5_pass/  --outputs mod_basecalls  --reference /genomes/hg38.fa --mod-motif Z CG 0 --processes 10`

Thanks

**Comment by marcus1487** [comment]
It looks like you might need to upgrade the ont_fast5_api dependency (`pip install -U ont_fast5_api`)
