### ISSUE TITLE
Unexpected errors in Megalodon v2.3.5

### ISSUE THREAD

**Issue by billytcl** [nanoporetech/megalodon#210]
I started to run Megalodon v2.3.5 to try and fix the hanging issue from v2.3.4, but now I'm getting a new error:

```
3 most common unsuccessful processing stages:
     6.5% (  39807 reads) : Unexpected error  
     1.4% (   8356 reads) : No alignment 
```

It created a new file, unexpected_megalodon_errors.6845.err, which has:

```
fast5_combined/PAH86296_pass_3c4dec9c_8387.fast5:::8424e48c-b84d-4974-b328-4f75eec6e06a
:::
Traceback (most recent call last):
  File "/home/billylau/.conda/envs/megalodon/lib/python3.8/site-packages/megalodon/megalodon.py", line 138, in handle_errors
    out_q.put((func(*args), r_vals))
  File "/home/billylau/.conda/envs/megalodon/lib/python3.8/site-packages/megalodon/mods.py", line 1728, in call_read_mods
    all_mods_seq, per_mod_seqs = get_mod_annotated_seqs(
  File "/home/billylau/.conda/envs/megalodon/lib/python3.8/site-packages/megalodon/mods.py", line 1420, in get_mod_annotated_seqs
    per_mod_seqs = format_mm_ml_tags(
  File "/home/billylau/.conda/envs/megalodon/lib/python3.8/site-packages/megalodon/mods.py", line 1341, in format_mm_ml_tags
    mod_poss, probs = zip(*sorted(pos_probs))
ValueError: not enough values to unpack (expected 2, got 0)
```

The initial log is:
```
[10:45:48] Running Megalodon version 2.3.5
DBG 10:45:48 : Command: """/home/billylau/.conda/envs/megalodon/bin/megalodon fast5_combined/ --guppy-server-path /mnt/ix1/Resources/tools/ont-guppy/v5.0.16/bin/guppy_basecall_server --guppy-config dna_r9.4.1_450bps_modbases_5mc_hac_prom.cfg --outputs basecalls mappings mod_mappings mods per_read_mods --reference /mnt/ix1/Resources/GenomeRef/Homo_sapiens/Ensembl/GRCh38_no_alt/Sequence/WholeGenomeFasta/hs38_naa.fna --mod-motif m CG 0 --devices 0 --processes 40 --samtools-executable /mnt/ix1/Resources/tools/samtools/v1.13/samtools --write-mods-text --output-directory ./megalodon""" --- MainProcess-MainThread megalodon.py:1761
[10:45:48] Loading guppy basecalling backend
DBG 10:45:48 : Guppy version: "5.0.16" --- MainProcess-MainThread backends.py:896
DBG 10:45:48 : Pyguppy version: "5.0.16" --- MainProcess-MainThread backends.py:897
DBG 10:45:48 : guppy server init command: "/mnt/ix1/Resources/tools/ont-guppy/v5.0.16/bin/guppy_basecall_server -p auto -l ./megalodon/guppy_log -c dna_r9.4.1_450bps_modbases_5mc_hac_prom.cfg --quiet --post_out -x cuda:0" --- MainProcess-MainThread backends.py:972
DBG 10:45:48 : Found guppy log file: ./megalodon/guppy_log/guppy_basecall_server_log-2021-11-01_10-45-48.log --- MainProcess-MainThread backends.py:988
DBG 10:45:57 : Connecting to server --- MainProcess-MainThread backends.py:830
DBG 10:45:57 : pyguppy server status: result.success --- MainProcess-MainThread backends.py:867
DBG 10:45:57 : pyguppy server config: {'/mnt/ix1/Resources/tools/ont-guppy/v5.0.16/data/dna_r9.4.1_450bps_modbases_5mc_hac_prom.cfg': {'Basecalling': {'ModelFile': 'template_r9.4.1_450bps_modbases_5mc_hac_prom.jsn', 'template_r9.4.1_450bps_modbases_5mc_hac_prom.jsn': {'version': {}}}}, 'config load results': {'m_name': 'config_loader', '/mnt/ix1/Resources/tools/ont-guppy/v5.0.16/data/dna_r9.4.1_450bps_modbases_5mc_hac_prom.cfg': {'status': 'loaded', 'failed_reason': ''}}} --- MainProcess-MainThread backends.py:869
DBG 10:45:57 : init_test_read BasecallingCompleted --- MainProcess-MainThread backends.py:1155
[10:45:57] Loading reference
[10:47:23] Loaded model calls canonical alphabet ACGT and modified bases m=5mC (alt to C)
[10:47:23] Preparing workers to process reads
```

**Comment by marcus1487** [comment]
We have found this internally as well. A fix has been pushed to github and will be included in the next release.

**Comment by billytcl** [comment]
Can you explain more about what is causing this error? Are they reads that would have otherwise been discarded? The reason why I'm asking is whether I should wait until the next release or keep running this without the fix, which will take ~5 days.

**Comment by marcus1487** [comment]
The error is related to reads which did not have any hits to the `--mod-motif`. So no modified base calls would have been output when this error is hit. There will be reads missing from mod_basecalls and mod_mappings, but they would not have contained any modified base calls. I would recommend that you do not have to re-run megalodon with this bug fixed.
