### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/home/z/MegalodonTest/ont-guppy/bin/'

### ISSUE THREAD

**Issue by CSU-ZeyuZhong** [nanoporetech/megalodon#218]
Hey there, I got a problem while running megalodon. The detail result is following:
```
[08:34:48] Running Megalodon version 2.3.5
[08:34:48] Loading guppy basecalling backend
Traceback (most recent call last):
  File "/home/zy/anaconda3/envs/Megalodon/bin/megalodon", line 8, in <module>
    sys.exit(_main())
  File "/home/z/anaconda3/envs/Megalodon/lib/python3.6/site-packages/megalodon/__main__.py", line 726, in _main
    megalodon._main(args)
  File "/home/z/anaconda3/envs/Megalodon/lib/python3.6/site-packages/megalodon/megalodon.py", line 1770, in _main
    model_info = backends.ModelInfo(backend_params, args.processes)
  File "/home/z/anaconda3/envs/Megalodon/lib/python3.6/site-packages/megalodon/backends.py", line 571, in __init__
    self.pyguppy_load_settings()
  File "/home/z/anaconda3/envs/Megalodon/lib/python3.6/site-packages/megalodon/backends.py", line 1088, in pyguppy_load_settings
    self.pyguppy_check_version(pyguppy_version_str)
  File "/home/z/anaconda3/envs/Megalodon/lib/python3.6/site-packages/megalodon/backends.py", line 881, in pyguppy_check_version
    stderr=subprocess.STDOUT,
  File "/home/z/anaconda3/envs/Megalodon/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/home/z/anaconda3/envs/Megalodon/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/z/MegalodonTest/ont-guppy/bin/'
```

I put ont-guppy everywhere but it still not worked. Also I use chmod to every files to 777 and I got the root but it didnt work. By the way the ont-guppy I used is 4.2.2 for CPU.

I will be very appreciated for solving my problem. Thanks a lot.

**Comment by CSU-ZeyuZhong** [comment]
the command I used is
`megalodon fast5_files/ --guppy-params "-d /home/z/rerio-master/basecall_models/" --guppy-config res_dna_r941_min_modbases_5mC_CpG_v001.cfg --outputs basecalls mappings mod_mappings mods --reference reference.fasta --output-directory all_results/ --guppy-server-path /home/z/MegalodonTest/ont-guppy/bin/ --mod-motif m CG 0 --processes 20 --overwrite `

**Comment by carissableker** [comment]
For future visitors - the issue is that the argument for `--guppy-server-path` should be the full path to the  guppy executable (not the bin folder) e.g `/home/bla/ble//ont-guppy/bin/guppy_basecall_server`.
