### ISSUE TITLE
megalodon_extras aggregate run, log.aggregation.re_aggregated.txt not found

### ISSUE THREAD

**Issue by danrdanny** [nanoporetech/megalodon#220]
I'm working to separate the megalodon steps in order to optimize GPU utilization. Using megalodon 2.3.5. If I stop megalodon during the aggregation step and run `megalodon_extras aggregate run` I get the following error:

```
Traceback (most recent call last):
  File "/net/software/modules-sw/megalodon/2.3.5/Linux/CentOS7/x86_64/megalodon_env/bin/megalodon_extras", line 8, in <module>
    sys.exit(_main())
  File "/net/software/modules-sw/megalodon/2.3.5/Linux/CentOS7/x86_64/megalodon_env/lib/python3.7/site-packages/megalodon_extras/__main__.py", line 225, in _main
    module._main(args)
  File "/net/software/modules-sw/megalodon/2.3.5/Linux/CentOS7/x86_64/megalodon_env/lib/python3.7/site-packages/megalodon_extras/aggregate_run.py", line 23, in _main
    logging.init_logger(args.megalodon_directory, out_suffix=log_suffix)
  File "/net/software/modules-sw/megalodon/2.3.5/Linux/CentOS7/x86_64/megalodon_env/lib/python3.7/site-packages/megalodon/logging.py", line 57, in init_logger
    log_fp = logging.FileHandler(log_fn, "w")
  File "/net/software/modules-sw/miniconda/4.8.3/Linux/CentOS7/x86_64/envs/python3/lib/python3.7/logging/__init__.py", line 1087, in __init__
    StreamHandler.__init__(self, self._open())
  File "/net/software/modules-sw/miniconda/4.8.3/Linux/CentOS7/x86_64/envs/python3/lib/python3.7/logging/__init__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/megalodon_results/log.aggregation.re_aggregated.txt'
```

The directory I'm running this command in contains the following:
```
basecalls.fastq
guppy_log
log.txt
mappings.bam
mappings.summary.txt
modified_bases.5mC.bed
mod_mappings.5mC.bam
per_read_modified_base_calls.db
sequencing_summary.txt
```

Do I need to do something before doing the aggregation step?

**Comment by marcus1487** [comment]
Could you provide the full command used? This error indicates that you have provided the megalodon results path of `/path/to/megalodon_results/`. This should likely be replaced with the actual path to your results to be aggregated.

**Comment by danrdanny** [comment]
Thanks for the reply @marcus1487. I didn't realize you need to give it a path--I just ran `megalodon_extras aggregate run` in the results directory. Are the full command options documented somewhere? Apologies if it's somewhere obvious and I'm not seeing it. I checked `https://nanoporetech.github.io/megalodon/extras_aggregate.html` as well and didn't see anything specific documented.

```
$ megalodon_extras aggregate --help
usage: megalodon_extras aggregate [-h] {run} ...

        run                           Run aggregation

optional arguments:
  -h, --help  show this help message and exit
```

**Comment by marcus1487** [comment]
`megalodon_extras aggregate run -h`

**Comment by danrdanny** [comment]
Thanks @marcus1487, didn't even think to check the command that way. I realize this is bothersome for you, but I really appreciate the time you took and hopefully other users like me will find this post and won't have to ask the same question.
