### ISSUE TITLE
Megalodon ignores "--use_tcp" from guppy6

### ISSUE THREAD

**Issue by billytcl** [nanoporetech/megalodon#225]
When trying to use TCP instead of IPC, I get the following from the megalodon log:

```
[billylau@sh03-ln06 login /scratch/groups/hanleeji/ONT_test/20211011_PRM_1096/megalodon_test_BL/barcode25_remora]$ cat log.txt 
[01:14:30] Running Megalodon version 2.4.0
DBG 01:14:30 : Command: """/home/users/billylau/.local/bin/megalodon fast5_combined/barcode25 --guppy-server-path /home/users/billylau/ont-guppy/bin/guppy_basecall_server --guppy-params "--use_tcp" --guppy-config dna_r9.4.1_450bps_sup_prom.cfg --remora-modified-bases dna_r9.4.1_e8 sup 0.0.0 5mc CG 0 --outputs basecalls mappings mod_mappings mods per_read_mods --reference /home/groups/hanleeji/Resources/GenomeRef/Homo_sapiens/Ensembl/GRCh38_no_alt/hs38_naa.fna --mod-motif m CG 0 --devices 0 --processes 40 --samtools-executable /home/users/billylau/.local/bin/samtools --write-mods-text --output-directory ./megalodon_test_BL/barcode25_remora""" --- MainProcess-MainThread megalodon.py:1793
[01:14:30] Loading guppy basecalling backend
DBG 01:14:32 : Guppy version: "6.0.0" --- MainProcess-MainThread backends.py:923
DBG 01:14:32 : Pyguppy version: "6.0.0" --- MainProcess-MainThread backends.py:924
DBG 01:14:32 : guppy server init command: "/home/users/billylau/ont-guppy/bin/guppy_basecall_server -p auto -l ./megalodon_test_BL/barcode25_remora/guppy_log -c dna_r9.4.1_450bps_sup_prom.cfg --quiet -x cuda:0 "--use_tcp"" --- MainProcess-MainThread backends.py:999
DBG 01:14:32 : Found guppy log file: ./megalodon_test_BL/barcode25_remora/guppy_log/guppy_basecall_server_log-2021-12-12_01-14-32.log --- MainProcess-MainThread backends.py:1015
```

It seems to hang forever. When looking in the guppy log folder, I find:

```
[billylau@sh03-ln06 login /scratch/groups/hanleeji/ONT_test/20211011_PRM_1096/megalodon_test_BL/barcode25_remora/guppy_log]$ cat guppy_basecall_server_log-2021-12-12_01-14-32.log 
2021-12-12 01:14:32.582374 [guppy/message] ONT Guppy basecall server software version 6.0.0+ab79250, client-server API version 10.0.0
log path:            ./megalodon_test_BL/barcode25_remora/guppy_log
chunk size:          2000
chunks per runner:   256
max queued reads:    2000
num basecallers:     4
num socket threads:  2
max returned events: 50000
gpu device:          cuda:0
kernel path:         
runners per device:  12
2021-12-12 01:14:32.583547 [guppy/info] crashpad_handler not supported on this platform.
2021-12-12 01:14:32.584386 [guppy/info] Listening on port ipc:///tmp/9c36-83af-23b8-2d8c.
2021-12-12 01:14:32.597831 [guppy/info] lamp_arrangements arrangement folder not found: /home/users/billylau/ont-guppy/data/read_splitting/lamp_arrangements
2021-12-12 01:14:32.817785 [guppy/info] CUDA device 0 (compute 8.0) initialised, memory limit 42505273344B (42071162880B free)
2021-12-12 01:14:36.220761 [guppy/message] 
Config loaded:
config file:               /home/users/billylau/ont-guppy/data/dna_r9.4.1_450bps_sup_prom.cfg
model file:                /home/users/billylau/ont-guppy/data/template_r9.4.1_450bps_sup_prom.jsn
model version id           2021-05-05_dna_r9.4.1_promethion_768_922a514b
adapter scaler model file: None
2021-12-12 01:14:36.222709 [guppy/message] Starting server on port: ipc:///tmp/9c36-83af-23b8-2d8c
```

Edit: I should also say that I ran the command with escaped quotes around --use_tcp, because I got the following when I didnt:

```
(megalodon2.4.0) billylau@suzuki:/tmp/billylau/20210922_PRM_1080$ nohup megalodon fast5_combined/barcode25 --guppy-server-path /mnt/ix1/Resources/tools/ont-guppy/v6.0.0/bin/guppy_basecall_server --guppy-params "--use_tcp" --guppy-config dna_r9.4.1_450bps_sup_prom.cfg --remora-modified-bases dna_r9.4.1_e8 sup 0.0.0 5mc CG 0 --outputs basecalls mappings mod_mappings mods per_read_mods --reference /mnt/ix1/Resources/GenomeRef/Homo_sapiens/Ensembl/GRCh38_no_alt/hs38_naa.fna --mod-motif m CG 0 --devices 0 --processes 40 --samtools-executable /mnt/ix2/Experimental_tools/samtools-1.13/samtools --write-mods-text --output-directory ./megalodon_test_remora/barcode25 &
[2] 158891
(megalodon2.4.0) billylau@suzuki:/tmp/billylau/20210922_PRM_1080$ nohup: ignoring input and appending output to 'nohup.out'

[2]+  Exit 2                  nohup megalodon fast5_combined/barcode25 --guppy-server-path /mnt/ix1/Resources/tools/ont-guppy/v6.0.0/bin/guppy_basecall_server --guppy-params "--use_tcp" --guppy-config dna_r9.4.1_450bps_sup_prom.cfg --remora-modified-bases dna_r9.4.1_e8 sup 0.0.0 5mc CG 0 --outputs basecalls mappings mod_mappings mods per_read_mods --reference /mnt/ix1/Resources/GenomeRef/Homo_sapiens/Ensembl/GRCh38_no_alt/hs38_naa.fna --mod-motif m CG 0 --devices 0 --processes 40 --samtools-executable /mnt/ix2/Experimental_tools/samtools-1.13/samtools --write-mods-text --output-directory ./megalodon_test_remora/barcode25
(megalodon2.4.0) billylau@suzuki:/tmp/billylau/20210922_PRM_1080$ cat nohup.out 
usage: megalodon [-h] [--guppy-config GUPPY_CONFIG]
                 [--guppy-server-path GUPPY_SERVER_PATH] [--live-processing]
                 [--outputs {basecalls,mod_basecalls,mappings,per_read_variants,variants,variant_mappings,per_read_mods,mods,mod_mappings,signal_mappings,per_read_refs} [{basecalls,mod_basecalls,mappings,per_read_variants,variants,variant_mappings,per_read_mods,mods,mod_mappings,signal_mappings,per_read_refs} ...]]
                 [--output-directory OUTPUT_DIRECTORY] [--overwrite]
                 [--mappings-format {bam,cram,sam}] [--reference REFERENCE]
                 [--haploid] [--variant-filename VARIANT_FILENAME]
                 [--mod-motif BASE MOTIF REL_POSITION]
                 [--remora-modified-bases PORE BASECALL_MODEL_TYPE BASECALL_MODEL_VERSION MODIFIED_BASES REMORA_MODEL_TYPE REMORA_MODEL_VERSION]
                 [--processes PROCESSES] [--devices DEVICES [DEVICES ...]]
                 [--help-long] [--rna] [-v]
                 fast5s_dir
megalodon: error: argument --guppy-params: expected one argument
```

Edit 2: looking at the logs more, it looks like that the guppy server command gets confused when I escape the quotes, but megalodon won't init properly if I don't. So to do a workaround, I added a space to the "--use_tcp" guppy param option in megalodon. That seems to make it use a TCP port properly, but then I get another error:

```
(megalodon2.4.0) billylau@suzuki:/tmp/billylau/20210922_PRM_1080$ nohup megalodon fast5_combined/barcode25 --guppy-server-path /mnt/ix1/Resources/tools/ont-guppy/v6.0.0/bin/guppy_basecall_server --guppy-params "--use_tcp " --guppy-config dna_r9.4.1_450bps_sup_prom.cfg --remora-modified-bases dna_r9.4.1_e8 sup 0.0.0 5mc CG 0 --outputs basecalls mappings mod_mappings mods per_read_mods --reference /mnt/ix1/Resources/GenomeRef/Homo_sapiens/Ensembl/GRCh38_no_alt/hs38_naa.fna --mod-motif m CG 0 --devices 0 --processes 40 --samtools-executable /mnt/ix2/Experimental_tools/samtools-1.13/samtools --write-mods-text --output-directory ./megalodon_test_remora/barcode25 &
[2] 158978
(megalodon2.4.0) billylau@suzuki:/tmp/billylau/20210922_PRM_1080$ nohup: ignoring input and appending output to 'nohup.out'

(megalodon2.4.0) billylau@suzuki:/tmp/billylau/20210922_PRM_1080$ cat nohup.out 
[01:25:46] Running Megalodon version 2.4.0
[01:25:46] Loading guppy basecalling backend
Traceback (most recent call last):
  File "/home/billylau/.conda/envs/megalodon2.4.0/bin/megalodon", line 8, in <module>
    sys.exit(_main())
  File "/home/billylau/.conda/envs/megalodon2.4.0/lib/python3.9/site-packages/megalodon/__main__.py", line 754, in _main
    megalodon._main(args)
  File "/home/billylau/.conda/envs/megalodon2.4.0/lib/python3.9/site-packages/megalodon/megalodon.py", line 1803, in _main
    model_info = backends.ModelInfo(
  File "/home/billylau/.conda/envs/megalodon2.4.0/lib/python3.9/site-packages/megalodon/backends.py", line 590, in __init__
    self.pyguppy_load_settings(
  File "/home/billylau/.conda/envs/megalodon2.4.0/lib/python3.9/site-packages/megalodon/backends.py", line 1149, in pyguppy_load_settings
    self.pyguppy_set_model_attributes(
  File "/home/billylau/.conda/envs/megalodon2.4.0/lib/python3.9/site-packages/megalodon/backends.py", line 1037, in pyguppy_set_model_attributes
    self.pyguppy_client_connect()
  File "/home/billylau/.conda/envs/megalodon2.4.0/lib/python3.9/site-packages/megalodon/backends.py", line 852, in pyguppy_client_connect
    self.pyguppy_client_init()
  File "/home/billylau/.conda/envs/megalodon2.4.0/lib/python3.9/site-packages/megalodon/backends.py", line 840, in pyguppy_client_init
    self.client = self.pyguppy_GuppyBasecallerClient(
  File "/home/billylau/.conda/envs/megalodon2.4.0/lib/python3.9/site-packages/pyguppy_client_lib/pyclient.py", line 122, in __init__
    self.set_params(self.params)
  File "/home/billylau/.conda/envs/megalodon2.4.0/lib/python3.9/site-packages/pyguppy_client_lib/pyclient.py", line 295, in set_params
    raise ValueError(
ValueError: Could not set server parameter 'state_data_enabled' using value True
[2]+  Exit 1                  nohup megalodon fast5_combined/barcode25 --guppy-server-path /mnt/ix1/Resources/tools/ont-guppy/v6.0.0/bin/guppy_basecall_server --guppy-params "--use_tcp " --guppy-config dna_r9.4.1_450bps_sup_prom.cfg --remora-modified-bases dna_r9.4.1_e8 sup 0.0.0 5mc CG 0 --outputs basecalls mappings mod_mappings mods per_read_mods --reference /mnt/ix1/Resources/GenomeRef/Homo_sapiens/Ensembl/GRCh38_no_alt/hs38_naa.fna --mod-motif m CG 0 --devices 0 --processes 40 --samtools-executable /mnt/ix2/Experimental_tools/samtools-1.13/samtools --write-mods-text --output-directory ./megalodon_test_remora/barcode25

(megalodon2.4.0) billylau@suzuki:/tmp/billylau/20210922_PRM_1080/megalodon_test_remora/barcode25/guppy_log$ cat guppy_basecall_server_log-2021-12-12_01-25-46.log 
2021-12-12 01:25:46.796161 [guppy/message] ONT Guppy basecall server software version 6.0.0+ab79250, client-server API version 10.0.0
log path:            ./megalodon_test_remora/barcode25/guppy_log
chunk size:          2000
chunks per runner:   256
max queued reads:    2000
num basecallers:     4
num socket threads:  2
max returned events: 50000
gpu device:          cuda:0
kernel path:         
runners per device:  12
2021-12-12 01:25:46.796320 [guppy/info] crashpad_handler not supported on this platform.
2021-12-12 01:25:46.797449 [guppy/info] Listening on port 35825.
2021-12-12 01:25:46.800766 [guppy/info] lamp_arrangements arrangement folder not found: /mnt/ix1/Resources/tools/ont-guppy/v6.0.0/data/read_splitting/lamp_arrangements
2021-12-12 01:25:49.071325 [guppy/info] CUDA device 0 (compute 8.6) initialised, memory limit 25447170048B (25178996736B free)
2021-12-12 01:25:50.348685 [guppy/message] 
Config loaded:
config file:               /mnt/ix1/Resources/tools/ont-guppy/v6.0.0/data/dna_r9.4.1_450bps_sup_prom.cfg
model file:                /mnt/ix1/Resources/tools/ont-guppy/v6.0.0/data/template_r9.4.1_450bps_sup_prom.jsn
model version id           2021-05-05_dna_r9.4.1_promethion_768_922a514b
adapter scaler model file: None
2021-12-12 01:25:50.351188 [guppy/message] Starting server on port: 35825
```

**Comment by marcus1487** [comment]
This final bug you have hit is an issue with a breaking change in Guppy6. We are working on a fix for this now and will include this in a new release shortly. 

The handling of the quotes is the interaction of unix and megalodon. Without spaces in the `"--use_tcp"` command, unix removes the quotes before passing to python and thus megalodon receives `--use_tcp` directly as an argument. Adding the space within the quotes is a perfectly fine workaround.

**Comment by marcus1487** [comment]
I've just pushed a patch release with support for Guppy 6.0.0 including the fix for this issue. Please re-open this issue if these issues persist with v2.4.1.
