### ISSUE TITLE
megalodon.megalodon_helper.MegaError: Data covering index does not exist.

### ISSUE THREAD

**Issue by Fatihlrcfs** [nanoporetech/megalodon#257]
hi all,

ı am working on megalodon with the command below.  I need .bed file but end of the run ı am getting this error. Do anyone know what is  the problem and how can ı fix it. many thanks. 

code : qsub -pe smp 40 -jc 4week -M 2397405@dundee.ac.uk -m ae -cwd -b y -R y megalodon fast5_skip/ --outputs mods --reference wholegenome.fasta --mod-motif m CG 0 --write-mods-text --processes 40 --guppy-server-path /cluster/lrcfs/2397405/bin/ont-guppy-cpu-6.0.1/bin/guppy_basecall_server --guppy-params "-d /cluster/lrcfs/2397405/bin/rerio/basecall_models/ --num_callers 40" --guppy-timeout 400 --guppy-config res_dna_r941_min_modbases_5mC_CpG_v001.cfg --overwrite 

error:
Read Processing: 100%|██████████| 2250353/2250353 [297:09:58<00:00,  2.10reads/s, samples/s=6.37e+4]

 input queue capacity extract_signal      :   0%|          | 0/10000    

output queue capacity per_read_mods       :   0%|          | 0/10000
[21:19:56] Unsuccessful processing types:
    20.5% ( 460505 reads) : Guppy server timeout (see --guppy-timeout argument)                             
    10.2% ( 229349 reads) : No alignment                                                                    
Process per_read_mods:
Traceback (most recent call last):
  File "/cluster/lrcfs/ftiras/ftiras_env/envs/nanoplot/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/cluster/lrcfs/ftiras/ftiras_env/envs/nanoplot/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/cluster/lrcfs/ftiras/ftiras_env/envs/nanoplot/lib/python3.8/site-packages/megalodon/mods.py", line 2103, in _get_mods_queue
    mods_db.create_data_covering_index()
  File "/cluster/lrcfs/ftiras/ftiras_env/envs/nanoplot/lib/python3.8/site-packages/megalodon/mods.py", line 845, in create_data_covering_index
    self.cur.execute(
sqlite3.OperationalError: unable to open database file
Traceback (most recent call last):
  File "/cluster/lrcfs/ftiras/ftiras_env/envs/nanoplot/bin/megalodon", line 11, in <module>
    sys.exit(_main())
  File "/cluster/lrcfs/ftiras/ftiras_env/envs/nanoplot/lib/python3.8/site-packages/megalodon/__main__.py", line 754, in _main
    megalodon._main(args)
  File "/cluster/lrcfs/ftiras/ftiras_env/envs/nanoplot/lib/python3.8/site-packages/megalodon/megalodon.py", line 1852, in _main
    aggregate.aggregate_stats(
  File "/cluster/lrcfs/ftiras/ftiras_env/envs/nanoplot/lib/python3.8/site-packages/megalodon/aggregate.py", line 454, in aggregate_stats
    agg_mods = mods.AggMods(mods_db_fn)
  File "/cluster/lrcfs/ftiras/ftiras_env/envs/nanoplot/lib/python3.8/site-packages/megalodon/mods.py", line 2835, in __init__
    self.mods_db.check_data_covering_index_exists()
  File "/cluster/lrcfs/ftiras/ftiras_env/envs/nanoplot/lib/python3.8/site-packages/megalodon/mods.py", line 293, in check_data_covering_index_exists
    raise mh.MegaError("Data covering index does not exist.")
megalodon.megalodon_helper.MegaError: Data covering index does not exist.

**Comment by marcus1487** [comment]
It looks as though there is an error overwritten by the progress bars. Could you post the end of the log.txt file produced?

**Comment by Fatihlrcfs** [comment]
hi Marcus,

thanks for your response. I am adding the last 25 lines of log.txt file 

DBG 21:19:56 : JoiningMain: Mapper033 --- MainProcess-MainThread megalodon.py:995
DBG 21:19:56 : JoinedMain: Mapper033 --- MainProcess-MainThread megalodon.py:997
DBG 21:19:56 : JoiningMain: Mapper034 --- MainProcess-MainThread megalodon.py:995
DBG 21:19:56 : JoinedMain: Mapper034 --- MainProcess-MainThread megalodon.py:997
DBG 21:19:56 : JoiningMain: Mapper035 --- MainProcess-MainThread megalodon.py:995
DBG 21:19:56 : JoinedMain: Mapper035 --- MainProcess-MainThread megalodon.py:997
DBG 21:19:56 : JoiningMain: Mapper036 --- MainProcess-MainThread megalodon.py:995
DBG 21:19:56 : JoinedMain: Mapper036 --- MainProcess-MainThread megalodon.py:997
DBG 21:19:56 : JoiningMain: Mapper037 --- MainProcess-MainThread megalodon.py:995
DBG 21:19:56 : JoinedMain: Mapper037 --- MainProcess-MainThread megalodon.py:997
DBG 21:19:56 : JoiningMain: Mapper038 --- MainProcess-MainThread megalodon.py:995
DBG 21:19:56 : JoinedMain: Mapper038 --- MainProcess-MainThread megalodon.py:997
DBG 21:19:56 : JoiningMain: Mapper039 --- MainProcess-MainThread megalodon.py:995
DBG 21:19:56 : JoinedMain: Mapper039 --- MainProcess-MainThread megalodon.py:997
DBG 21:19:56 : JoiningMain: Getters --- MainProcess-MainThread megalodon.py:1000
[21:19:56] Waiting for mods database to complete indexing
DBG 21:19:56 : JoiningMain: per_read_mods --- MainProcess-MainThread megalodon.py:1012
DBG 21:19:56 : GetterClosing --- per_read_mods-MainThread mods.py:2084
DBG 21:19:56 : GetterClosing --- failed_reads-MainThread megalodon.py:849
[21:19:56] Unsuccessful processing types:
    20.5% ( 460505 reads) : Guppy server timeout (see --guppy-timeout argument)
    10.2% ( 229349 reads) : No alignment
DBG 21:19:56 : CreatingIndex --- per_read_mods-MainThread mods.py:2102
DBG 21:21:07 : JoinedMain: per_read_mods --- MainProcess-MainThread megalodon.py:1014
DBG 21:21:07 : JoiningMain: Complete --- MainProcess-MainThread megalodon.py:1015
