### ISSUE TITLE
how to use Taiyaki trained model for modified base calling in megalodon

### ISSUE THREAD

**Issue by ThomasSaturn** [nanoporetech/megalodon#260]
Hi,

i'm intending to obtain a model from taiyaki to identify a modified base, using a intermediate model file from taiyaki model training and the following script:
`megalodon ${fast5} \
        --taiyaki-model-filename ${model} \
        --do-not-use-guppy-server \
        --overwrite \
        --rna \
        --device cpu \
        --process 4 \
        --outputs mod_basecalls`
after running the script, i got this error message: `[17:32:33] Running Megalodon version 2.4.2
******************** WARNING: Quality score computation not enabled for taiyaki or FAST5 backends. Quality scores will be invalid. ********************
[17:32:33] Loading taiyaki basecalling backend
Traceback (most recent call last):
  File "****/tools/miniconda3/envs/megalodon/bin/megalodon", line 8, in <module>
    sys.exit(_main())
  File "****/tools/miniconda3/envs/megalodon/lib/python3.7/site-packages/megalodon/__main__.py", line 754, in _main
    megalodon._main(args)
  File "****/tools/miniconda3/envs/megalodon/lib/python3.7/site-packages/megalodon/megalodon.py", line 1811, in _main
    args, mods_info = parse_mod_args(args, model_info, map_info)
  File "****/tools/miniconda3/envs/megalodon/lib/python3.7/site-packages/megalodon/megalodon.py", line 1500, in parse_mod_args
    remora_sig_map_offset=sig_map_shift,
  File "****/tools/miniconda3/envs/megalodon/lib/python3.7/site-packages/megalodon/mods.py", line 2337, in __init__
    LOGGER.info(model_info.get_alphabet_str())
  File "****/tools/miniconda3/envs/megalodon/lib/python3.7/site-packages/megalodon/backends.py", line 510, in get_alphabet_str
    if self.is_mod_model:
AttributeError: 'ModelInfo' object has no attribute 'is_mod_model'`

Is there any documentation for usage method or a walkthrough on this? Thank you

**Comment by marcus1487** [comment]
The `--taiyaki-model-filename` option is quite experimental and intended only for new neural network architectures. For standard model structures (including modified bases) the recommendation is to run taiyaki/bin/dump_json.py and use the produced model via the Guppy backend to Megalodon.

**Comment by marcus1487** [comment]
I would also highly recommend using Remora for modified base model training. These models are more robust and higher accuracy while allowing use of simpler training samples than basecaller-integrated modified base models (as trained from Taiyaki directly).
