### ISSUE TITLE
Modifications calling without guppy or tayaki ?

### ISSUE THREAD

**Issue by pterzian** [nanoporetech/megalodon#30]
Hi Marcus,

It is a very naive question I have. I followed the instruction and create a conda env for megalodon and I was happy to finally try it out personally. **I am mainly interested in mods calling**.

I got this error :
```
******************** WARNING: Quality score computation not enabled for taiyaki or FAST5 backends. Quality scores will be invalid. ********************
[14:39:30] Loading FAST5 basecalling backend.
Traceback (most recent call last):
  File "/home/pterzian/.conda/envs/megalodonenv/bin/megalodon", line 11, in <module>
    sys.exit(_main())
  File "/home/pterzian/.conda/envs/megalodonenv/lib/python3.6/site-packages/megalodon/megalodon.py", line 1212, in _main
    with backends.ModelInfo(backend_params, args.processes) as model_info:
  File "/home/pterzian/.conda/envs/megalodonenv/lib/python3.6/site-packages/megalodon/backends.py", line 407, in __init__
    self._load_fast5_post_out()
  File "/home/pterzian/.conda/envs/megalodonenv/lib/python3.6/site-packages/megalodon/backends.py", line 285, in _load_fast5_post_out
    self.output_size) = get_model_info_from_fast5(read)
  File "/home/pterzian/.conda/envs/megalodonenv/lib/python3.6/site-packages/megalodon/backends.py", line 266, in get_model_info_from_fast5
    out_size = fast5_io.get_posteriors(read).shape[1]
  File "/home/pterzian/.conda/envs/megalodonenv/lib/python3.6/site-packages/megalodon/fast5_io.py", line 76, in get_posteriors
    '--post_out were set when running guppy.')
megalodon.megalodon_helper.MegaError: StateData not found in FAST5 file. Ensure --fsat5_out and --post_out were set when running guppy.
```

When running this command :

```
megalodon cp_fast5/ \
    --outputs basecalls mods \
    --reference reference.fa \
    --mod-motif Z CG 0 --devices 0 --processes 10 \
    --verbose-read-progress 3 \
    --do-not-use-guppy-server \
    --overwrite
```

In the documentation I read "The path to the guppy_basecall_server executable is required to run megalodon" but I found this argument `--do-not-use-guppy-server` in the full documentation (and naively hoped it would help).

So I guess I am missing something ! Maybe it is my environment or the raw fast5 files format ?

Best,

Paul

**Comment by marcus1487** [comment]
The `--do-not-use-guppy-server` option is intended for the run-mode when the full neural network output has been saved to the fast5 files. Note in the error message that `--fast5_out` (typo in the real message needs to be fixed) and `--post_out` must be set when running guppy in order to use the fast5 run mode. If you re-run guppy with these flags, then this run mode should work. Note that this guppy option will generally add 5-10X to the size of the FAST5 files. 

There used to be more documentation on this before the direct guppy run mode was added. I will attempt to find a place for this documentation again.
