### ISSUE TITLE
missing /ont-guppy/bin/guppy_basecall_server'

### ISSUE THREAD

**Issue by joscarhuguet** [nanoporetech/megalodon#34]
Thanks for the tool.

Just installed and run it.
even we re-installed guppy_basecall_server
I think I am missing some modules? 

[11:33:37] Loading guppy basecalling backend.
Traceback (most recent call last):
  File "/apps/megalodon/2.0.0/bin/megalodon", line 11, in <module>
    sys.exit(_main())
  File "/apps/megalodon/2.0.0/lib/python3.7/site-packages/megalodon/megalodon.py", line 1212, in _main
    with backends.ModelInfo(backend_params, args.processes) as model_info:
  File "/apps/megalodon/2.0.0/lib/python3.7/site-packages/megalodon/backends.py", line 403, in __init__
    self._load_pyguppy()
  File "/apps/megalodon/2.0.0/lib/python3.7/site-packages/megalodon/backends.py", line 393, in _load_pyguppy
    start_guppy_server()
  File "/apps/megalodon/2.0.0/lib/python3.7/site-packages/megalodon/backends.py", line 340, in start_guppy_server
    stdout=self.guppy_out_fp, stderr=self.guppy_err_fp)
  File "/apps/megalodon/2.0.0/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/apps/megalodon/2.0.0/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './ont-guppy/bin/guppy_basecall_server': './ont-guppy/bin/guppy_basecall_server'
~

**Comment by marcus1487** [comment]
By default Megalodon, expects Guppy to be installed in the working directory. If this is not the case, you can provide the path to the guppy_basecall_server executable via the `—guppy-server-path` argument. See docs [here](https://nanoporetech.github.io/megalodon/common_arguments.html#guppy-backend-argument). 

This error message could certainly be more helpful though. I will update this processing to provide a more helpful error message.

**Comment by marcus1487** [comment]
This error message was update with version 2.1 to include a pointer to the `—guppy-server-path` argument.
