### ISSUE TITLE
Sqlite version incompatibilities when calling modifications

### ISSUE THREAD

**Issue by pesteller** [nanoporetech/megalodon#64]
Hello,

I was running megalodon (v2.2.3) and it worked fine for basecalling and do the mapping. However, when trying to call modifications with the mods argument I get the following error message:
 
[19:41:22] Loading guppy basecalling backend
[2020-10-15 19:41:23.823377] [0x00007faae1cd1700] [info]    Connecting to server as
[19:41:24] Loading reference
******************** WARNING: "mods" output requested, so "per_read_mods" will be added to outputs. ********************
[19:41:24] Using canonical alphabet ACGT and modified bases Y=6mA (alt to A); Z=5mC (alt to C)
Traceback (most recent call last):
  File "/scratch/devel/pesteller/test/megalodon_env/bin/megalodon", line 8, in <module>
    sys.exit(_main())
  File "/scratch/devel/pesteller/test/megalodon_env/lib/python3.7/site-packages/megalodon/__main__.py", line 430, in _main
    megalodon._main(args)
  File "/scratch/devel/pesteller/test/megalodon_env/lib/python3.7/site-packages/megalodon/megalodon.py", line 1233, in _main
    args, model_info, ref_out_info, map_info)
  File "/scratch/devel/pesteller/test/megalodon_env/lib/python3.7/site-packages/megalodon/megalodon.py", line 1005, in parse_mod_args
    mods_db = mods.ModsDb(mods_info.mods_db_fn, read_only=True)
  File "/scratch/devel/pesteller/test/megalodon_env/lib/python3.7/site-packages/megalodon/mods.py", line 132, in __init__
    self.establish_db_conn()
  File "/scratch/devel/pesteller/test/megalodon_env/lib/python3.7/site-packages/megalodon/mods.py", line 163, in establish_db_conn
    self.db = sqlite3.connect('file:' + self.fn + '?mode=ro', uri = True)
sqlite3.NotSupportedError: URIs not supported

Following the recommendations of a [similar](https://github.com/pretix/pretix/issues/1155) problem in django, if I set uri to false in line 163 of the mods.py script, the error message changes to (also in line 163):
sqlite3.OperationalError: unable to open database file

Is this due to sqlite3 version differences? Which sqlite version do you recommend using? I am currently using sqlite version 3.33.0. 

For megalodon to work I have replaced this line of code from **self.db = sqlite3.connect('file:' + self.fn + '?mode=ro', uri = True)** to **self.db = sqlite3.connect(self.fn)** but I don't really know if this is the best way to proceed. What do you think? 

Many thanks

**Comment by marcus1487** [comment]
It looks like this might have been solved in python 3.4. Megalodon only supports python >=3.5, so this shouldn't be happening as far as I can tell. Is this a custom install on an older python version?

This workaround seems fine to me. The read only opening of the database was a protection against accidental changes to the database (really only applicable when used via the API/outside of standard command line functions) and potentially could save some compute or IO time. But if these are not concerns then this patch should work just fine.

**Comment by pesteller** [comment]
Thanks for your reply. That's actually weird because megalodon was installed in python 3.7.5 so this should not be an issue. It could be that I installed this program in my institution's cluster with some settings that I am not aware of. Anyways, I'll use this workaround and hopefully it will be enough to process the data I have.
Thanks

**Comment by marcus1487** [comment]
Is it possible that your cluster has a non-standard build of python. It looks like there can be issues if python was built against an older version of sqlite. How are you determining the sqlite version? Could you try `python -c "import sqlite3; print(sqlite3.version); print(sqlite3.sqlite_version)"` with the version of python used for the Megalodon install?

**Comment by pesteller** [comment]
The default sqlites I got when installing megalodon were sqlite3 2.6.0 and sqlite version 3.6.20 but then I updated it to sqlite version 3.33.0. Sorry if this makes no sense but I'm new in the sqlite world and I don't really know how it works.
In short, the command you suggest`(python -c "import sqlite3; print(sqlite3.version); print(sqlite3.sqlite_version)") `was 2.6.0 and 3.6.20 when I installed megalodon but after installing a newer version of sqlite now it is 2.6.0 and 3.33.0.

**Comment by marcus1487** [comment]
It sounds like a reinstallation might help here. If you could reinstall megalodon in a new virtual environment (after confirming the sqlite versions are updated) might help isolate this issue as well.

**Comment by pesteller** [comment]
I reinstalled megalodon (now version 2.2.4) with sqlite3 version 2.6.0 and sqlite version 3.32.2 but the problem persists for `mods`. Also, I have not tried this yet but I guess the same problem will be found for `--outputs variants` since line 129 from env_name/lib/python3.7/site-packages/megalodon/variants.py is equivalent to line 163 in mods.py.

**Comment by marcus1487** [comment]
I am not able to reproduce this issue. I suspect that this might have to do with a custom python installation (with non-standard settings). Is this possible?

**Comment by marcus1487** [comment]
Closing due to inactivity. Please re-open if issues remain.
