### ISSUE TITLE
Error initialising guppy_basecall_server?

### ISSUE THREAD

**Issue by ulbivin** [nanoporetech/megalodon#66]
Hi,

I try to run Megalodon with the following command:
$ megalodon fast5_pass/ --outputs basecalls mappings mod_mappings mods --reference /media/nano/Storage1/reference_seq/hg38.fa --mod-motif Z CG 0 --devices 0 --processes 1 --guppy-server-path /opt/ont/guppy/bin/guppy_basecall_server --output-directory /media/nano/Storage1/ONT_data/megalodon_out/ --overwrite

I get the following output, and after a short while error mesage:

[15:02:16] Running Megalodon version 2.2.4
[15:02:16] Loading guppy basecalling backend
[2020-11-03 15:02:18.373610] [0x00007f6eca177740] [info]    Connecting to server as 
[2020-11-03 15:02:26.400012] [0x00007f6eca177740] [info]    Exception disconnecting from server with ID 1. Operation cannot be accomplished in current state
Traceback (most recent call last):
  File "/home/nano/anaconda3/bin/megalodon", line 8, in <module>
    sys.exit(_main())
  File "/home/nano/anaconda3/lib/python3.8/site-packages/megalodon/__main__.py", line 430, in _main
    megalodon._main(args)
  File "/home/nano/anaconda3/lib/python3.8/site-packages/megalodon/megalodon.py", line 1228, in _main
    model_info = backends.ModelInfo(backend_params, args.processes)
  File "/home/nano/anaconda3/lib/python3.8/site-packages/megalodon/backends.py", line 646, in __init__
    self._load_pyguppy()
  File "/home/nano/anaconda3/lib/python3.8/site-packages/megalodon/backends.py", line 637, in _load_pyguppy
    set_pyguppy_model_attributes()
  File "/home/nano/anaconda3/lib/python3.8/site-packages/megalodon/backends.py", line 590, in set_pyguppy_model_attributes
    init_called_read, _, _ = next(self.pyguppy_basecall(
StopIteration

Could this be a problem when backends.py initialise guppy_basecall_server? This seems to be running fine on its own though:
Guppy Basecall Service Software, (C) Oxford Nanopore Technologies, Limited. Version 4.2.2+effbaf84, client-server API version 3.2.0

Any help is much appreciated!

**Comment by marcus1487** [comment]
Yes, this certainly looks like an issue with the initialization of the guppy basecall server. Could you provide the context of the `log.txt` file in the megalodon output directory to assist in further debugging this issue?

**Comment by ulbivin** [comment]
Hi Marcus,

Thank you, for getting back to me, the log.txt reads:

[15:02:16] Running Megalodon version 2.2.4
DBG 15:02:16 : Command: """/home/nano/anaconda3/bin/megalodon fast5_pass/ --outputs basecalls mappings mod_mappings mods --reference /media/nano/Storage1/reference_seq/hg38.fa --mod-motif Z CG 0 --devices 0 --processes 1 --guppy-server-path /opt/ont/guppy/bin/guppy_basecall_server --output-directory /media/nano/Storage1/ONT_data/megalodon_out/ --overwrite""" --- MainProcess-MainThread megalodon.py:1219
[15:02:16] Loading guppy basecalling backend
DBG 15:02:16 : Guppy version: "4.2.2" --- MainProcess-MainThread backends.py:500
DBG 15:02:16 : Pyguppy version: "4.2.2" --- MainProcess-MainThread backends.py:501
DBG 15:02:16 : guppy server init command: "/opt/ont/guppy/bin/guppy_basecall_server -p auto -l /media/nano/Storage1/ONT_data/megalodon_out/guppy_log -c dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg --post_out -x cuda:0" --- MainProcess-MainThread backends.py:558
DBG 15:02:26 : init_test_read BasecallingFailed Pyguppy get completed reads invalid error "Something went wrong. return_code: result.failed" --- MainProcess-MainThread backends.py:905

**Comment by marcus1487** [comment]
This indicates that the guppy server has failed to process the small test read during initialization. This generally occurs when there is a high load on the compute resources. Could this be the case in this setting?

**Comment by ulbivin** [comment]
I have another quite heavy process running so this actually could be the issue. I will try to run it again once this is completed.

**Comment by ulbivin** [comment]
Hi Marcus,
It turns out that I have the process guppy_basecall_ (root) running at all times taking up about 5% of a single CPU core. I can terminate the process but it emediately restarts. After I reboot the computer the process is still running, but I can run Megalodon which initialises guppy basecall server as intended and everything is working. I do however have the process guppy_basecall_ running twice, the one I started using much more CPU depending on --processes, the one at 5%, and Megalodon has its own process. After the job completes, I still have the guppy_basecall_ running at 5%, but now I cannot run Megalodon again until I reboot. I am a bit puzzled by all of this. It seems the problem lies with the guppy basecaller, but if you have any suggestions to resolve this matter I would be happy to hear them.

**Comment by marcus1487** [comment]
This is an unexpected behavior. This indeed seems to be an issue with the guppy server. I don't have any immediate inclination as to why this is happening or how to fix this. I will try to see if this is a known guppy server issue.

**Comment by marcus1487** [comment]
It looks like this might be an issue with using the same guppy installation that is used in MinKNOW. The reason for the guppy_basecall_server processes in the background and on restart is likely the MinKNOW installation on this machine. 

Could you try to install (just download and unzip for installation) guppy from the archives [here](https://community.nanoporetech.com/downloads)? Then point Megalodon to this installation. Hopefully this resolves this issue.

**Comment by marcus1487** [comment]
Did this latest recommendation resolve this issue?

**Comment by marcus1487** [comment]
Closing due to inactivity. Please re-open if issues remain.

**Comment by jazsakr** [comment]
Hello! @marcus1487, I tried what you suggested on 11/9/2022, however I still have the same issue.

Here is the command I ran:
```
megalodon ./fast5 --guppy-config dna_r9.4.1_450bps_modbases_5mc_cg_sup.cfg --guppy-server-path ~/ont-guppy/ont-guppy_6.1.3/bin/guppy_basecall_server --sort-mappings --write-mods-text --mod-map-emulate-bisulfite --mod-map-base-conv C T --mod-map-base-conv m C --outputs mod_basecalls mappings mod_mappings per_read_mods mods --reference ~/references/genome.fa --devices cuda:0,1 --output-directory basecalling_megalodon --overwrite
```

---

This is the error message I got:

```
[11:04:16] Running Megalodon version 2.5.0
[11:04:16] Loading guppy basecalling backend
****************************************************************************************************
	ERROR: Error running initial Guppy test read. Likely a timeout error. Consider increasing --guppy-timeout 
****************************************************************************************************
```

---

Here is what is written in `log.txt`:
```
[11:04:16] Running Megalodon version 2.5.0
DBG 11:04:16 : Command: """/home/jsakr/.local/bin/megalodon ./fast5 --guppy-config dna_r9.4.1_450bps_modbases_5mc_cg_sup.cfg --guppy-server-path /home/jsakr/ont-guppy/ont-guppy_6.1.3/bin/gupp
y_basecall_server --sort-mappings --write-mods-text --mod-map-emulate-bisulfite --mod-map-base-conv C T --mod-map-base-conv m C --outputs mod_basecalls mappings mod_mappings per_read_mods mod
s --reference /home/jsakr/references/genome.fa --devices cuda:0,1 --output-directory basecalling_megalodon --overwrite""" --- MainProcess-MainThread megalodon.py:1787
[11:04:16] Loading guppy basecalling backend
DBG 11:04:16 : Guppy version: "6.1.3" --- MainProcess-MainThread backends.py:938
DBG 11:04:16 : Pyguppy version: "6.1.3" --- MainProcess-MainThread backends.py:939
DBG 11:04:16 : guppy server init command: "/home/jsakr/ont-guppy/ont-guppy_6.1.3/bin/guppy_basecall_server -p auto -l basecalling_megalodon_1/guppy_log -c dna_r9.4.1_450bps_modbases_5mc_cg_su
p.cfg --quiet --post_out -x cuda:0,1" --- MainProcess-MainThread backends.py:1016
DBG 11:04:16 : Found guppy log file: basecalling_megalodon_1/guppy_log/guppy_basecall_server_log-2022-05-18_11-04-16.log --- MainProcess-MainThread backends.py:1032
DBG 11:04:17 : Guppy server started on port ipc:///tmp/b9ba-5945-ad1a-ce04 --- MainProcess-MainThread backends.py:973
DBG 11:04:17 : Connecting to server --- MainProcess-MainThread backends.py:872
DBG 11:04:17 : pyguppy server status: result.success --- MainProcess-MainThread backends.py:909
DBG 11:04:17 : Could not load guppy server configuration state: 'Configurations' --- MainProcess-MainThread backends.py:913
DBG 11:06:17 : init_test_read BasecallingFailed Timeout --- MainProcess-MainThread backends.py:1275
****************************************************************************************************
	ERROR: Error running initial Guppy test read. Likely a timeout error. Consider increasing --guppy-timeout 
****************************************************************************************************
```

---

I added the `--guppy-timeout` flag and increased it to `10` then `20` and I still got the same error.

**Comment by yanchunzhang** [comment]
> Hello! @marcus1487, I tried what you suggested on 11/9/2022, however I still have the same issue.
> 
> Here is the command I ran:
> 
> ```
> megalodon ./fast5 --guppy-config dna_r9.4.1_450bps_modbases_5mc_cg_sup.cfg --guppy-server-path ~/ont-guppy/ont-guppy_6.1.3/bin/guppy_basecall_server --sort-mappings --write-mods-text --mod-map-emulate-bisulfite --mod-map-base-conv C T --mod-map-base-conv m C --outputs mod_basecalls mappings mod_mappings per_read_mods mods --reference ~/references/genome.fa --devices cuda:0,1 --output-directory basecalling_megalodon --overwrite
> ```
> 
> This is the error message I got:
> 
> ```
> [11:04:16] Running Megalodon version 2.5.0
> [11:04:16] Loading guppy basecalling backend
> ****************************************************************************************************
> 	ERROR: Error running initial Guppy test read. Likely a timeout error. Consider increasing --guppy-timeout 
> ****************************************************************************************************
> ```
> 
> Here is what is written in `log.txt`:
> 
> ```
> [11:04:16] Running Megalodon version 2.5.0
> DBG 11:04:16 : Command: """/home/jsakr/.local/bin/megalodon ./fast5 --guppy-config dna_r9.4.1_450bps_modbases_5mc_cg_sup.cfg --guppy-server-path /home/jsakr/ont-guppy/ont-guppy_6.1.3/bin/gupp
> y_basecall_server --sort-mappings --write-mods-text --mod-map-emulate-bisulfite --mod-map-base-conv C T --mod-map-base-conv m C --outputs mod_basecalls mappings mod_mappings per_read_mods mod
> s --reference /home/jsakr/references/genome.fa --devices cuda:0,1 --output-directory basecalling_megalodon --overwrite""" --- MainProcess-MainThread megalodon.py:1787
> [11:04:16] Loading guppy basecalling backend
> DBG 11:04:16 : Guppy version: "6.1.3" --- MainProcess-MainThread backends.py:938
> DBG 11:04:16 : Pyguppy version: "6.1.3" --- MainProcess-MainThread backends.py:939
> DBG 11:04:16 : guppy server init command: "/home/jsakr/ont-guppy/ont-guppy_6.1.3/bin/guppy_basecall_server -p auto -l basecalling_megalodon_1/guppy_log -c dna_r9.4.1_450bps_modbases_5mc_cg_su
> p.cfg --quiet --post_out -x cuda:0,1" --- MainProcess-MainThread backends.py:1016
> DBG 11:04:16 : Found guppy log file: basecalling_megalodon_1/guppy_log/guppy_basecall_server_log-2022-05-18_11-04-16.log --- MainProcess-MainThread backends.py:1032
> DBG 11:04:17 : Guppy server started on port ipc:///tmp/b9ba-5945-ad1a-ce04 --- MainProcess-MainThread backends.py:973
> DBG 11:04:17 : Connecting to server --- MainProcess-MainThread backends.py:872
> DBG 11:04:17 : pyguppy server status: result.success --- MainProcess-MainThread backends.py:909
> DBG 11:04:17 : Could not load guppy server configuration state: 'Configurations' --- MainProcess-MainThread backends.py:913
> DBG 11:06:17 : init_test_read BasecallingFailed Timeout --- MainProcess-MainThread backends.py:1275
> ****************************************************************************************************
> 	ERROR: Error running initial Guppy test read. Likely a timeout error. Consider increasing --guppy-timeout 
> ****************************************************************************************************
> ```
> 
> I added the `--guppy-timeout` flag and increased it to `10` then `20` and I still got the same error.

I got the same error and don't know why.

Yanchun

**Comment by Lex-mmm** [comment]
Dear all,

I have a similar error, but have not been able to solve it so far. 
I am trying to run megalodon (v2.5.0) on a super computer/ HPS system using a bash script. Log output is:

[11:49:37] Running Megalodon version 2.5.0
DBG 11:49:37 : Command: """/g/data/qq78/LeX/miniconda3/envs/rdna/bin/megalodon /g/data/qq78/rDNA/Cancer_lee/20221124_BT245_Parent_HMW_/20221124_0502_MN19343_FAU96512_ab255872/fast5_pass/ --guppy-params -d /g/data/qq78/LeX/ont-guppy/data --guppy-config dna_r9.4.1_450bps_hac_prom.cfg --output-directory /g/data/qq78/methylome/rDNA_cancer/test --guppy-server-path /g/data/qq78/LeX/ont-guppy/bin/guppy_basecall_server --outputs basecalls mappings mod_mappings mods per_read_mods --reference /g/data/qq78/rDNA/new_ref_cancer/adaptive_sampling_genes_cancer_lee.fasta --devices cuda:all --guppy-timeout 1000 --overwrite""" --- MainProcess-MainThread megalodon.py:1787
[11:49:37] Loading guppy basecalling backend
DBG 11:49:38 : Guppy version: "6.4.2" --- MainProcess-MainThread backends.py:938
DBG 11:49:38 : Pyguppy version: "6.4.2" --- MainProcess-MainThread backends.py:939
DBG 11:49:38 : guppy server init command: "/g/data/qq78/LeX/ont-guppy/bin/guppy_basecall_server -p auto -l /g/data/qq78/methylome/rDNA_cancer/test/guppy_log -c dna_r9.4.1_450bps_hac_prom.cfg --quiet --post_out -x cuda:all -d /g/data/qq78/LeX/ont-guppy/data" --- MainProcess-MainThread backends.py:1016
DBG 11:49:38 : Found guppy log file: /g/data/qq78/methylome/rDNA_cancer/test/guppy_log/guppy_basecall_server_log-2023-01-17_11-49-38.log --- MainProcess-MainThread backends.py:1032
DBG 11:49:41 : Guppy server started on port ipc:///jobfs/70017339.gadi-pbs/f4ef-b9ba-1e91-e03e --- MainProcess-MainThread backends.py:973
DBG 11:49:41 : Connecting to server --- MainProcess-MainThread backends.py:872
DBG 11:49:41 : pyguppy server status: result.success --- MainProcess-MainThread backends.py:909
DBG 11:49:41 : Could not load guppy server configuration state: 'Configurations' --- MainProcess-MainThread backends.py:913
DBG 11:51:44 : Get reads connection error  "Not connected to server. status code: <status.preparing_connection: 1>. <super: <class 'PyGuppyClient'>, <PyGuppyClient object>>" --- MainProcess-MainThread backends.py:1228
DBG 11:51:45 : Get reads connection error  "Not connected to server. status code: <status.loading_config: 2>. <super: <class 'PyGuppyClient'>, <PyGuppyClient object>>" --- MainProcess-MainThread backends.py:1228

I feel that a high load on the computer source is not the problem since the supercomputer you well be able to deal with this job.

Kind regards,
Lex

**Comment by kaufmanelij** [comment]
Hi @Lex-mmm were you able to resolve your issue? I believe I have the same error.

**Comment by CWYuan08** [comment]
Hi @kaufmanelij  @Lex-mmm @yanchunzhang @jazsakr @ulbivin @marcus1487 guys, have you fixed the problem? any help would be greatly appreciated!

**Comment by marcus1487** [comment]
Hi @CWYuan08 , megalodon is deprecated. I would highly recommend using Dorado or Guppy to produce modified basecalls.

**Comment by kaufmanelij** [comment]
@marcus1487 Would it be possible if the repo and official documentation could be updated to say that it is deprecated? and that ONT recommends the dorado _alpha_ or guppy? Unless I'm missing it, I was only told yesterday in a private chat with an ONT rep that megalodon was LIKELY deprecated.

**Comment by jazsakr** [comment]
@marcus1487 If it's deprecated, is there another Nanopore package that produces an output like Megalodon's `--write-mods-text`? If I'm not mistaken, neither Guppy nor Dorado produce such an output?

**Comment by marcus1487** [comment]
We are working on adding this functionality to the `modkit` package. The next release should have a per-read statistics output. Note that this will likely not match the megalodon format exactly, but will contain the same general per-read call information in a text table format.

We will add an official deprecation notice to this repository shortly.
