### ISSUE TITLE
Difficulties in installing Megalodon

### ISSUE THREAD

**Issue by nxiao6gt** [nanoporetech/megalodon#7]
When I type
pip install git+git://github.com/nanoporetech/megalodon.git

I receive the following error message. 
Collecting git+git://github.com/nanoporetech/megalodon.git
  Cloning git://github.com/nanoporetech/megalodon.git to /tmp/pip-req-build-ddvy0c6h
  Running command git clone -q git://github.com/nanoporetech/megalodon.git /tmp/pip-req-build-ddvy0c6h
Requirement already satisfied: h5py>=2.2.1 in ./anaconda3/lib/python3.7/site-packages (from megalodon==0.1.0) (2.9.0)
Requirement already satisfied: numpy>=1.9.0 in ./anaconda3/lib/python3.7/site-packages (from megalodon==0.1.0) (1.16.4)
Requirement already satisfied: Cython>=0.25.2 in ./anaconda3/lib/python3.7/site-packages (from megalodon==0.1.0) (0.29.12)
Requirement already satisfied: mappy>=2.16 in ./anaconda3/lib/python3.7/site-packages (from megalodon==0.1.0) (2.17)
Collecting pysam>=0.15 (from megalodon==0.1.0)
  Using cached https://files.pythonhosted.org/packages/15/e7/2dab8bb0ac739555e69586f1492f0ff6bc4a1f8312992a83001d3deb77ac/pysam-0.15.3.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: # pysam: cython is available - using cythonize if necessary
    # pysam: htslib mode is shared
    # pysam: HTSLIB_CONFIGURE_OPTIONS=None
    # pysam: (env) CC=/condo/ieg/nxiao6/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc
    # pysam: (env) CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe
    # pysam: (env) LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now
    checking for gcc... /condo/ieg/nxiao6/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether /condo/ieg/nxiao6/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc accepts -g... yes
    checking for /condo/ieg/nxiao6/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc option to accept ISO C89... none needed
    checking for ranlib... /condo/ieg/nxiao6/anaconda3/bin/x86_64-conda_cos6-linux-gnu-ranlib
    checking for grep that handles long lines and -e... /usr/bin/grep
    checking for C compiler warning flags... -Wall
    checking for special C compiler options needed for large files... no
    checking for _FILE_OFFSET_BITS value needed for large files... no
    checking for _LARGEFILE_SOURCE value needed for large files... no
    checking shared library type for unknown-Linux... plain .so
    checking how to run the C preprocessor... /condo/ieg/nxiao6/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cpp
    checking for egrep... /usr/bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for stdlib.h... (cached) yes
    checking for unistd.h... (cached) yes
    checking for sys/param.h... yes
    checking for getpagesize... yes
    checking for working mmap... yes
    checking for gmtime_r... yes
    checking for fsync... yes
    checking for drand48... yes
    checking whether fdatasync is declared... yes
    checking for fdatasync... yes
    checking for library containing log... -lm
    checking for zlib.h... no
    checking for inflate in -lz... no
    configure: error: zlib development files not found

    HTSlib uses compression routines from the zlib library <http://zlib.net>.
    Building HTSlib requires zlib development files to be installed on the build
    machine; you may need to ensure a package such as zlib1g-dev (on Debian or
    Ubuntu Linux) or zlib-devel (on RPM-based Linux distributions or Cygwin)
    is installed.

    FAILED.  This error must be resolved in order to build HTSlib successfully.
    checking for gcc... /condo/ieg/nxiao6/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether /condo/ieg/nxiao6/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc accepts -g... yes
    checking for /condo/ieg/nxiao6/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc option to accept ISO C89... none needed
    checking for ranlib... /condo/ieg/nxiao6/anaconda3/bin/x86_64-conda_cos6-linux-gnu-ranlib
    checking for grep that handles long lines and -e... /usr/bin/grep
    checking for C compiler warning flags... -Wall
    checking for special C compiler options needed for large files... no
    checking for _FILE_OFFSET_BITS value needed for large files... no
    checking for _LARGEFILE_SOURCE value needed for large files... no
    checking shared library type for unknown-Linux... plain .so
    checking how to run the C preprocessor... /condo/ieg/nxiao6/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cpp
    checking for egrep... /usr/bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for stdlib.h... (cached) yes
    checking for unistd.h... (cached) yes
    checking for sys/param.h... yes
    checking for getpagesize... yes
    checking for working mmap... yes
    checking for gmtime_r... yes
    checking for fsync... yes
    checking for drand48... yes
    checking whether fdatasync is declared... yes
    checking for fdatasync... yes
    checking for library containing log... -lm
    checking for zlib.h... no
    checking for inflate in -lz... no
    configure: error: zlib development files not found

    HTSlib uses compression routines from the zlib library <http://zlib.net>.
    Building HTSlib requires zlib development files to be installed on the build
    machine; you may need to ensure a package such as zlib1g-dev (on Debian or
    Ubuntu Linux) or zlib-devel (on RPM-based Linux distributions or Cygwin)
    is installed.

    FAILED.  This error must be resolved in order to build HTSlib successfully.
    make: ./version.sh: Command not found
    make: ./version.sh: Command not found
    config.mk:2: *** Resolve configure error first.  Stop.
    # pysam: htslib configure options: None
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-a6k09_wr/pysam/setup.py", line 241, in <module>
        htslib_make_options = run_make_print_config()
      File "/tmp/pip-install-a6k09_wr/pysam/setup.py", line 68, in run_make_print_config
        stdout = subprocess.check_output(["make", "-s", "print-config"])
      File "/condo/ieg/nxiao6/anaconda3/lib/python3.7/subprocess.py", line 395, in check_output
        **kwargs).stdout
      File "/condo/ieg/nxiao6/anaconda3/lib/python3.7/subprocess.py", line 487, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['make', '-s', 'print-config']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-a6k09_wr/pysam/

**Comment by marcus1487** [comment]
This appears to be an error related to installing the pysam prerequisite. This appears to be from a cached version of the pysam library. It may help to clear your pip cache and try to install again.

**Comment by marcus1487** [comment]
Was pysam able to be installed and did this fix this issue?

**Comment by mishtynegi** [comment]
Had the same issue while installing taiyaki. Was not resolved by clearing pip cache. However, reinstalling pysam in the conda env sorted the issue for me. For reference: [pysam installation](https://pysam.readthedocs.io/en/latest/installation.html). Proceed with installing megalodon in the taiyaki env.
