### ISSUE TITLE
"binary incompatibility" error after installation of 2.2.10

### ISSUE THREAD

**Issue by mollybrothers** [nanoporetech/megalodon#92]
Hello! I just updated megalodon from 2.2.8 to 2.2.10 (I missed 9!), but when I try running I get this error. Can't quite figure out what the issue is and hoping you might be able to help! Please let me know if I can give any other info. Thank you!

`Traceback (most recent call last):
  File "/global/home/users/molly_brothers/.conda/envs/guppy/bin/megalodon", line 11, in <module>
    sys.exit(_main())
  File "/global/home/users/molly_brothers/.conda/envs/guppy/lib/python3.7/site-packages/megalodon/__main__.py", line 443, in _main
    from megalodon import megalodon
  File "/global/home/users/molly_brothers/.conda/envs/guppy/lib/python3.7/site-packages/megalodon/megalodon.py", line 16, in <module>
    from megalodon import (
  File "/global/home/users/molly_brothers/.conda/envs/guppy/lib/python3.7/site-packages/megalodon/aggregate.py", line 9, in <module>
    from megalodon import (
  File "/global/home/users/molly_brothers/.conda/envs/guppy/lib/python3.7/site-packages/megalodon/mods.py", line 15, in <module>
    from megalodon import (
  File "megalodon/_decode.pyx", line 1, in init megalodon.decode
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject`

**Comment by marcus1487** [comment]
When using a source (github clone) install, when the cython code is changed the install must be run again. You should be able to run `pip install -e .` from the repo root (within your desired environment) in order to complete this re-compiling of the cython code. This should fix your installation. Please post if you still have issues after this step.

**Comment by mollybrothers** [comment]
Hi Marcus,

I should be able to try this later today. Is this still applicable if I used bioconda to install? I should have mentioned that.

**Comment by marcus1487** [comment]
It seems less likely in that case. In this case I would recommend removing any old installations before a re-install. Python may be finding an old installation for megalodon and using them at run time, but having the command line pointing to a different install. I would recommend running `conda uninstall megalodon` repeatedly until it tells you there is no such package installed and then retry `conda install megalodon`.

**Comment by mollybrothers** [comment]
Update: this worked!
